### ISSUE TITLE
ConsensusSet needs clean close

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1253]
I encountered this non-deterministic test failure which would be fixed using a `sync.ThreadGroup`.
```
panic: cannot write to the file after it has been closed
goroutine 2279 [running]:
panic(0x6659c0, 0xc820398a10)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/panic.go:464 +0x3ff
github.com/NebulousLabs/Sia/build.Critical(0xc8205a3d38, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/NebulousLabs/Sia/build/critical.go:13 +0xa2
github.com/NebulousLabs/Sia/persist.(*closeableFile).Write(0xc820454f60, 0xc820423000, 0x6f, 0x80, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/NebulousLabs/Sia/persist/log.go:102 +0x1bf
log.(*Logger).Output(0xc82074c870, 0x2, 0xc82029f180, 0x40, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/log/log.go:166 +0x482
github.com/NebulousLabs/Sia/persist.(*Logger).Debugln(0xc820751640, 0xc8205a3f50, 0x2, 0x2)
	/Users/travis/gopath/src/github.com/NebulousLabs/Sia/persist/log.go:48 +0x97
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).rpcRelayHeader.func2(0xc820229400, 0x21d0710, 0xc820341b20)
	/Users/travis/gopath/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:385 +0x30d
created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).rpcRelayHeader
	/Users/travis/gopath/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:387 +0x2e4
FAIL	github.com/NebulousLabs/Sia/modules/consensus	40.242s
```

**Comment by DavidVorick** [comment]
not surprising.

Is this a significant issue? I'm guessing it will be fairly invasive to add clean shutdown, given how sensitive the consensus code is.

**Comment by VoidingWarranties** [comment]
Beat you to it, sorry! I was encountering a lot of non deterministic test failures because of the lack of clean close. The consensus set doesn't have any long running goroutines so it was very straight forward. The only notable change is the need to have `cs.tg.Add` at the beginning of all methods registered with the gateway (RPC and OnConnect methods). In fact, an RPC method was responsible for the error above.
