### ISSUE TITLE
Error upon launch of Sia-UI-darwin

### ISSUE THREAD

**Issue by virl** [NebulousLabs/Sia#1441]
Sia-UI-v1.0.2-darwin-x64

macOS Sierra 10.12

![siabug](https://cloud.githubusercontent.com/assets/2991028/18717500/cc534fd2-8028-11e6-9379-f63396eea017.png)

```
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1337:33)
    at Object.config.save (/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:3622:17)
    at configManager (/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:3633:10)
    at Object.isNumeric (/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:74:39)
    at __webpack_require__ (/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:20:30)
    at /private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:40:18
    at Object.<anonymous> (/private/var/folders/3t/hp3bqxcd4cgcr6fydlbkzc4c0000gn/T/AppTranslocation/FF3B4B99-BADC-4E03-9B21-3EFCC3546208/d/Sia-UI.app/Contents/Resources/app/dist/main.js:43:10)
```

**Comment by lukechampine** [comment]
It looks like you are trying to launch Sia from a directory without write permissions. Try installing it in another directory.

**Comment by virl** [comment]
@lukechampine I'm launching Sia app in folder that was unpacked from its .zip release bundle.

**Comment by DavidVorick** [comment]
did you unpack it as admin?

'read-only file system' often indicatees disk problems, I don't think this is an issue with Sia

**Comment by virl** [comment]
@DavidVorick I've unpacked it as regular OS X user and launched it as regular user.

Basically, I unpacked and launched it as any other OS X GUI App.

**Comment by lukechampine** [comment]
it looks like "App Translocation" is to blame: http://lapcatsoftware.com/articles/app-translocation.html

basically, OS X doesn't trust our binary, so it secretly moves it to a read-only temp folder and runs it there. It seems you can get around this by moving the app to a different folder, e.g. `~/Downloads/Sia/`.

**Comment by DavidVorick** [comment]
Sia performs a lot more disk I/O than most applications, it's likely that a standard application would not pick up on the issues.

It says that it is trying to save to '/private/var/folders' - are you sure that the application has write permissions there? I'm not super familiar with how OS X works, but nobody else has been reporting this issue and we have a large number of OS X users.

**Comment by virl** [comment]
@DavidVorick Maybe it's because I'm launching it on macOS Sierra that was released today?

**Comment by virl** [comment]
@DavidVorick @lukechampine Ok, app works if I first move it to Applications folder.
