### ISSUE TITLE
Renter started reporting negative currency

### ISSUE THREAD

**Issue by lolsteve** [NebulousLabs/Sia#1561]
And my allowance is showing as 0 SC

``` 
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1 [running]:
runtime/debug.Stack(0x7a, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420141428, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:19 +0xb7
github.com/NebulousLabs/Sia/types.Currency.Sub(0x3aa000, 0x0, 0x0, 0x0, 0x0, 0xc420128570, 0x2, 0x5, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:183 +0x16c
main.rentercmd()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/rentercmd.go:124 +0x1bf
reflect.Value.call(0x3299e0, 0x3dce80, 0x13, 0x3a94d5, 0x4, 0x58e1e0, 0x0, 0x0, 0xc420039a88, 0x25ee1, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x3299e0, 0x3dce80, 0x13, 0x58e1e0, 0x0, 0x0, 0xc420039af0, 0x1ca826, 0x32ab00)
	/usr/local/go/src/reflect/value.go:302 +0xa4
main.wrap.func1(0x56aa60, 0xc420102440, 0x0, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/main.go:211 +0x1e3
github.com/spf13/cobra.(*Command).execute(0x56aa60, 0xc4201023b0, 0x1, 0x1, 0x56aa60, 0xc4201023b0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc420096d80, 0x1, 0x3be2fc, 0x4d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc420096d80, 0x570560, 0x3a960d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/main.go:275 +0xc34
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1 [running]:
runtime/debug.Stack(0x7a, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420141428, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:19 +0xb7
github.com/NebulousLabs/Sia/types.Currency.Sub(0x3aa000, 0x0, 0x0, 0x0, 0x0, 0xc4201285a0, 0x2, 0x5, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:183 +0x16c
main.rentercmd()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/rentercmd.go:124 +0x21d
reflect.Value.call(0x3299e0, 0x3dce80, 0x13, 0x3a94d5, 0x4, 0x58e1e0, 0x0, 0x0, 0xc420039a88, 0x25ee1, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x3299e0, 0x3dce80, 0x13, 0x58e1e0, 0x0, 0x0, 0xc420039af0, 0x1ca826, 0x32ab00)
	/usr/local/go/src/reflect/value.go:302 +0xa4
main.wrap.func1(0x56aa60, 0xc420102440, 0x0, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/main.go:211 +0x1e3
github.com/spf13/cobra.(*Command).execute(0x56aa60, 0xc4201023b0, 0x1, 0x1, 0x56aa60, 0xc4201023b0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc420096d80, 0x1, 0x3be2fc, 0x4d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc420096d80, 0x570560, 0x3a960d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siac/main.go:275 +0xc34
Renter info:
	Storage Spending:  1.505 SC
	Upload Spending:   165.8 mS
	Download Spending: 0 H
	Unspent Funds:     0 H
	Total Allocated:   0 H

Tracking 60 files:
```

**Comment by lukechampine** [comment]
this should be fixed now. Please reopen if it recurs in v1.3.0.
