### ISSUE TITLE
Stall+hang during download

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1567]
Tried downloading a file. Froze at 99.2%. After Ctrl-C, it appears to have deadlocked.

These are the goroutines implicated in the deadlock:
```
goroutine 1 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc42012c224)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42012c218)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/NebulousLabs/Sia/sync.(*ThreadGroup).Stop(0xc42012c1c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/sync/threadgroup.go:140 +0x138
github.com/NebulousLabs/Sia/modules/renter.(*Renter).Close(0xc4200a6210, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:185 +0x32
main.startDaemon.func9(0xcbb600, 0xc4200a6210)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:256 +0xc7
main.startDaemon(0x0, 0x0, 0xa028fc, 0xe, 0x9f2160, 0x5, 0x9f2165, 0x5, 0x0, 0x9f71ba, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:298 +0xad7
main.startDaemonCmd(0xc420099440, 0xdca100, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420099440, 0xc42000c2c0, 0x0, 0x0, 0xc420099440, 0xc42000c2c0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc420099440, 0xa1b468, 0x3b, 0xc42017cb40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc420099440, 0xdad220, 0xa0740e)
	/home/luke/go/src/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:171 +0x742
```
and many of these:
```
goroutine 208 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc42012c20c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42012c208)
	/usr/local/go/src/sync/mutex.go:85 +0xd0
github.com/NebulousLabs/Sia/sync.(*ThreadGroup).Add(0xc42012c1c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/sync/threadgroup.go:53 +0x4c
github.com/NebulousLabs/Sia/modules/renter.(*worker).threadedWorkLoop(0xc420576780)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/worker.go:220 +0x6a
created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).updateWorkerPool
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/worker.go:252 +0x64a
```
I'll investigate more tomorrow.

**Comment by DavidVorick** [comment]
the worker pool threads are probably just workers waiting for work, if there's nothing to do you'd expect to see them paused.

If you were at 99.2% there was likely only 1 or 2 pieces left. With 42 workers, only 1 worker can be operating at a time for each piece.

It's possible that the repairState somehow dropped a piece and did not even realize that it still had work to do.
