### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Hedde** [NebulousLabs/Sia#1616]
Possible steps to reproduce (MacOS Sierra 10.12.3):

- download the daemon (1.1.2)
- start the daemon
- while the daemon is still syncing download the sia-UI
- start the sia-UI

I'm not really experienced with sia yet, but perhaps you can't run the daemon and UI at the same time, because the UI tries to start a daemon itself or some collision occurs?

**Stacktrace**

`Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.e.save (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10717)
    at o (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10792)
    at Object.0 (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:449)
    at e (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:186)
    at t.0.t.__esModule.default (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:273)
    at Object.<anonymous> (/private/var/folders/sl/pzjv37hn5gv7_dgc1x9xx7l80000gn/T/AppTranslocation/01D09376-DE11-40D8-BC7B-4933E8D0FA90/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:278)`

**Comment by johnathanhowell** [comment]
This is caused by App Translocation. If you move Sia-UI.app to your /Applications folder it should work fine.

**Comment by Hedde** [comment]
@johnathanhowell thanks, that makes sense, although probably worth mentioning on the downloads page. I think MacOS provides an internal API to display a "move required" action when opening an executable from within the downloads folder. Regards.
