### ISSUE TITLE
Users have started reporting consensus errors

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1629]
`2017/03/31 12:22:25.801383 subscribe.go:54: CRITICAL: getBlockMap failed in computeConsensusChange: requested item does not exist`

We have started having users (multiple) provide consensus.db logs with the above error. That should not be happening at all, so hopefully we can track down the issue.

**Comment by DcyMatrix** [comment]
Is this error enough of a problem to not setup Sia 1.12 at the moment?

The reason I am asking is that I am in the process of setting up a Sia Host, and if it would be better to wait with announcing the host till a new version I'd like to know, before things gets messed up ;-)

**Comment by DavidVorick** [comment]
I'm not sure what the issue is, but at least one user has reported that the issue is because they were misuing the client (they had two instances of 'siad' using the same persist folders over a network drive - this caused the filesystem locks to fail, so instead of one returning an error they just modified eachothers databases and corrupted it).

I don't know if the other users had similarly incorrect configurations, so I'm leaving this open until we have more clarity on the issue.

This should not affect a host at all, if your consensus database corrupts, it's easy enough to fix without destroying your files or contracts or anything.

**Comment by DavidVorick** [comment]
```
https://pastebin.com/jPx49Q0Wunexpected fault address 0xc42f100000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc42f100000 pc=0x926715]

goroutine 36 [running]:
runtime.throw(0xcd33e1, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4280f8f30 sp=0xc4280f8f10
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4280f8f80 sp=0xc4280f8f30
github.com/NebulousLabs/bolt.(*node).write(0xc420938000, 0xc42f0ffff0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/node.go:205 +0x185 fp=0xc4280f90f8 sp=0xc4280f8f80
github.com/NebulousLabs/bolt.(*Bucket).write(0xc4280f9270, 0x68, 0x9, 0xc42629a2a0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:598 +0x11f fp=0xc4280f9158 sp=0xc4280f90f8
github.com/NebulousLabs/bolt.(*Bucket).CreateBucket(0xc4239629b8, 0x1042740, 0x9, 0x9, 0xc4200776b0, 0x1, 0x5)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:181 +0x4da fp=0xc4280f92b8 sp=0xc4280f9158
github.com/NebulousLabs/bolt.(*Tx).CreateBucket(0xc4239629a0, 0x1042740, 0x9, 0x9, 0xa74f4b5d7c75c5f4, 0x94013b80e924d514, 0xbacfadd1515681ae)
	/home/user/dev/src/github.com/NebulousLabs/bolt/tx.go:108 +0x61 fp=0xc4280f9318 sp=0xc4280f92b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).createChangeLog(0xc42395ea00, 0xc4239629a0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/changelog.go:134 +0x88 fp=0xc4280f9488 sp=0xc4280f9318
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initDB(0xc42395ea00, 0xc4239629a0, 0xc420078ea0, 0xc427281260)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/database.go:102 +0x99 fp=0xc4280f9518 sp=0xc4280f9488
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB.func1(0xc4239629a0, 0xd071c0, 0xc4239629a0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:36 +0x3a8 fp=0xc4280f9660 sp=0xc4280f9518
github.com/NebulousLabs/bolt.(*DB).Update(0xc4272810e0, 0xc42ab87700, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/db.go:595 +0xc7 fp=0xc4280f96b8 sp=0xc4280f9660
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc42395ea00, 0xc42629a090, 0xc42f0fe3c0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:54 +0x1d7 fp=0xc4280f9740 sp=0xc4280f96b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc42395ea00, 0xc42629a070, 0x2)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:82 +0x25a fp=0xc4280f97e0 sp=0xc4280f9740
github.com/NebulousLabs/Sia/modules/consensus.New(0x104e720, 0xc4259306e0, 0x0, 0xc429248390, 0x2b, 0xc4259306e0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:139 +0x8b3 fp=0xc4280f9b50 sp=0xc4280f97e0
github.com/NebulousLabs/Sia/api.assembleServerTester(0xc7cfa1936203db3d, 0x307ce9cb51056d8f, 0x80f1eb5a18e4ac01, 0x952a8bb8283b1325, 0xc427c290b0, 0x21, 0x48c07e, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:159 +0x233 fp=0xc4280f9d88 sp=0xc4280f9b50
github.com/NebulousLabs/Sia/api.createServerTester(0xce23b5, 0xd, 0x1, 0x3, 0xc420020600)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:385 +0x19f fp=0xc4280f9ec0 sp=0xc4280f9d88
github.com/NebulousLabs/Sia/api.TestApiClient(0xc42007cea0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/client_test.go:14 +0xb8 fp=0xc4280f9f88 sp=0xc4280f9ec0
testing.tRunner(0xc42007cea0, 0xd06be0)
	/usr/local/go/src/testing/testing.go:657 +0x108 fp=0xc4280f9fd0 sp=0xc4280f9f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4280f9fd8 sp=0xc4280f9fd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x544unexpected fault address 0xc42f100000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc42f100000 pc=0x926715]

goroutine 36 [running]:
runtime.throw(0xcd33e1, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4280f8f30 sp=0xc4280f8f10
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4280f8f80 sp=0xc4280f8f30
github.com/NebulousLabs/bolt.(*node).write(0xc420938000, 0xc42f0ffff0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/node.go:205 +0x185 fp=0xc4280f90f8 sp=0xc4280f8f80
github.com/NebulousLabs/bolt.(*Bucket).write(0xc4280f9270, 0x68, 0x9, 0xc42629a2a0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:598 +0x11f fp=0xc4280f9158 sp=0xc4280f90f8
github.com/NebulousLabs/bolt.(*Bucket).CreateBucket(0xc4239629b8, 0x1042740, 0x9, 0x9, 0xc4200776b0, 0x1, 0x5)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:181 +0x4da fp=0xc4280f92b8 sp=0xc4280f9158
github.com/NebulousLabs/bolt.(*Tx).CreateBucket(0xc4239629a0, 0x1042740, 0x9, 0x9, 0xa74f4b5d7c75c5f4, 0x94013b80e924d514, 0xbacfadd1515681ae)
	/home/user/dev/src/github.com/NebulousLabs/bolt/tx.go:108 +0x61 fp=0xc4280f9318 sp=0xc4280f92b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).createChangeLog(0xc42395ea00, 0xc4239629a0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/changelog.go:134 +0x88 fp=0xc4280f9488 sp=0xc4280f9318
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initDB(0xc42395ea00, 0xc4239629a0, 0xc420078ea0, 0xc427281260)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/database.go:102 +0x99 fp=0xc4280f9518 sp=0xc4280f9488
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB.func1(0xc4239629a0, 0xd071c0, 0xc4239629a0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:36 +0x3a8 fp=0xc4280f9660 sp=0xc4280f9518
github.com/NebulousLabs/bolt.(*DB).Update(0xc4272810e0, 0xc42ab87700, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/db.go:595 +0xc7 fp=0xc4280f96b8 sp=0xc4280f9660
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc42395ea00, 0xc42629a090, 0xc42f0fe3c0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:54 +0x1d7 fp=0xc4280f9740 sp=0xc4280f96b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc42395ea00, 0xc42629a070, 0x2)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:82 +0x25a fp=0xc4280f97e0 sp=0xc4280f9740
github.com/NebulousLabs/Sia/modules/consensus.New(0x104e720, 0xc4259306e0, 0x0, 0xc429248390, 0x2b, 0xc4259306e0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:139 +0x8b3 fp=0xc4280f9b50 sp=0xc4280f97e0
github.com/NebulousLabs/Sia/api.assembleServerTester(0xc7cfa1936203db3d, 0x307ce9cb51056d8f, 0x80f1eb5a18e4ac01, 0x952a8bb8283b1325, 0xc427c290b0, 0x21, 0x48c07e, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:159 +0x233 fp=0xc4280f9d88 sp=0xc4280f9b50
github.com/NebulousLabs/Sia/api.createServerTester(0xce23b5, 0xd, 0x1, 0x3, 0xc420020600)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:385 +0x19f fp=0xc4280f9ec0 sp=0xc4280f9d88
github.com/NebulousLabs/Sia/api.TestApiClient(0xc42007cea0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/client_test.go:14 +0xb8 fp=0xc4280f9f88 sp=0xc4280f9ec0
testing.tRunner(0xc42007cea0, 0xd06be0)
	/usr/local/go/src/testing/testing.go:657 +0x108 fp=0xc4280f9fd0 sp=0xc4280f9f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4280f9fd8 sp=0xc4280f9fd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x544unexpected fault address 0xc42f100000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc42f100000 pc=0x926715]

goroutine 36 [running]:
runtime.throw(0xcd33e1, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4280f8f30 sp=0xc4280f8f10
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4280f8f80 sp=0xc4280f8f30
github.com/NebulousLabs/bolt.(*node).write(0xc420938000, 0xc42f0ffff0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/node.go:205 +0x185 fp=0xc4280f90f8 sp=0xc4280f8f80
github.com/NebulousLabs/bolt.(*Bucket).write(0xc4280f9270, 0x68, 0x9, 0xc42629a2a0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:598 +0x11f fp=0xc4280f9158 sp=0xc4280f90f8
github.com/NebulousLabs/bolt.(*Bucket).CreateBucket(0xc4239629b8, 0x1042740, 0x9, 0x9, 0xc4200776b0, 0x1, 0x5)
	/home/user/dev/src/github.com/NebulousLabs/bolt/bucket.go:181 +0x4da fp=0xc4280f92b8 sp=0xc4280f9158
github.com/NebulousLabs/bolt.(*Tx).CreateBucket(0xc4239629a0, 0x1042740, 0x9, 0x9, 0xa74f4b5d7c75c5f4, 0x94013b80e924d514, 0xbacfadd1515681ae)
	/home/user/dev/src/github.com/NebulousLabs/bolt/tx.go:108 +0x61 fp=0xc4280f9318 sp=0xc4280f92b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).createChangeLog(0xc42395ea00, 0xc4239629a0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/changelog.go:134 +0x88 fp=0xc4280f9488 sp=0xc4280f9318
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initDB(0xc42395ea00, 0xc4239629a0, 0xc420078ea0, 0xc427281260)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/database.go:102 +0x99 fp=0xc4280f9518 sp=0xc4280f9488
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB.func1(0xc4239629a0, 0xd071c0, 0xc4239629a0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:36 +0x3a8 fp=0xc4280f9660 sp=0xc4280f9518
github.com/NebulousLabs/bolt.(*DB).Update(0xc4272810e0, 0xc42ab87700, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/bolt/db.go:595 +0xc7 fp=0xc4280f96b8 sp=0xc4280f9660
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc42395ea00, 0xc42629a090, 0xc42f0fe3c0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:54 +0x1d7 fp=0xc4280f9740 sp=0xc4280f96b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc42395ea00, 0xc42629a070, 0x2)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:82 +0x25a fp=0xc4280f97e0 sp=0xc4280f9740
github.com/NebulousLabs/Sia/modules/consensus.New(0x104e720, 0xc4259306e0, 0x0, 0xc429248390, 0x2b, 0xc4259306e0, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:139 +0x8b3 fp=0xc4280f9b50 sp=0xc4280f97e0
github.com/NebulousLabs/Sia/api.assembleServerTester(0xc7cfa1936203db3d, 0x307ce9cb51056d8f, 0x80f1eb5a18e4ac01, 0x952a8bb8283b1325, 0xc427c290b0, 0x21, 0x48c07e, 0x0, 0x0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:159 +0x233 fp=0xc4280f9d88 sp=0xc4280f9b50
github.com/NebulousLabs/Sia/api.createServerTester(0xce23b5, 0xd, 0x1, 0x3, 0xc420020600)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/server_helpers_test.go:385 +0x19f fp=0xc4280f9ec0 sp=0xc4280f9d88
github.com/NebulousLabs/Sia/api.TestApiClient(0xc42007cea0)
	/home/user/dev/src/github.com/NebulousLabs/Sia/api/client_test.go:14 +0xb8 fp=0xc4280f9f88 sp=0xc4280f9ec0
testing.tRunner(0xc42007cea0, 0xd06be0)
	/usr/local/go/src/testing/testing.go:657 +0x108 fp=0xc4280f9fd0 sp=0xc4280f9f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4280f9fd8 sp=0xc4280f9fd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x544
```

^ this may be related

**Comment by DcyMatrix** [comment]
Thanks you! @davidVorick
Will continue with setting up my gear :-)

**Comment by lukechampine** [comment]
was this ever addressed? Haven't seen any other reports of this bug crop up lately. There are new bugs in the consensusdb, but we have separate issues for those.

**Comment by tbenz9** [comment]
No response from OP, no recent reports of this error.

Recommendation: Close
