### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by l3stat** [NebulousLabs/Sia#1717]
On OSX Sierra 10.12.4 using Sia-UI 1.4.15

Siad has exited unexpectedly. Please submit a bug report including the error log here.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.116028633 seconds

**Comment by DavidVorick** [comment]
There was no other output?

hmm. There's no error reported other than the unexpected exit. Did you get a popup, or some other notification.

Did it happen while you were unlocking the wallet?

My thoughts:

1. Might have been an out-of-memory error (fix inbound)
2. Might have been an out-of-files error (fix also inbound)

**Comment by l3stat** [comment]
Yes it was when I was unlocking the wallet. So far no luck unlocking the wallet at all. I thought you had instant wallet unlocking, is that not available on OSX?

Also, when I just double click on Sia-UI I get this:

---

A JavaScript error occurred in the main process

Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.e.save (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10717)
    at o (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10792)
    at Object.0 (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:449)
    at e (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:186)
    at t.0.t.__esModule.default (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:273)
    at Object.<anonymous> (/private/var/folders/9y/j5mbp_sj77b6w7m7cf4tn8kh0000gn/T/AppTranslocation/EDC5EA04-4201-451B-90B7-ED40517427F6/d/Sia-UI.app/Contents/Resources/app/dist/main.js:1:278)

---

It only works if I right click then select “Open”

**Comment by lukechampine** [comment]
This looks like the OS X App Translocation bug. Try moving Sia to a different folder: https://siawiki.tech/client/troubleshooting
