### ISSUE TITLE
Sia-UI: siad on OSX crashes while unlocking wallet

### ISSUE THREAD

**Issue by adno** [NebulousLabs/Sia#1750]
I am using "v1.2.1 (Blue Moon)" on OS X and I am unable to unlock my wallet. The blockchain is synchronized and the passphrase accepted, but for a long time a message about the wallet in the process of being unlocked ("may take several minutes") is displayed and then:

Siad has exited unexpectedly. Please submit a bug report including the error log here.

```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.819651164 seconds

Wallet: scanned to height 67308...
<snip>
Wallet: scanned to height 79241...
Wallet: scanned to height 79292...
Wallet: scanned to height 79308...goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4204b35f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4204b3948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffccc, 0xe, 0x7fff5fbffcf8, 0x5, 0x7fff5fbffce7, 0x5, 0x0, 0x7fff5fbffd08, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420081200, 0xc4200194a0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420081200, 0xc42000e0d0, 0x5, 0x5, 0xc420081200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0xc420081200, 0x16c6004, 0x3b, 0xc4201548c0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420081200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
```

**Comment by johnathanhowell** [comment]
Can you try unlocking using just `siad` and `siac` to determine if this is a `Sia-UI` problem?

**Comment by adno** [comment]
It seems that it was a problem with the wallet files. I re-inited the 
wallet from seed and now it works correctly even in the Sia-UI.

-- 
Adam Nohejl

**Comment by ds2000** [comment]
Sorry for being dumb, I'm having the same on 1.2.2.  I've increased the ulimit, waited for the blockchain to sync but the wallet keeps crashing with the same error mentioned.

Any tips or commands to resolve this?  Being relatively new "I re-inited the wallet from seed" hasn't turned much up for me yet.

Thanks

Dave
