### ISSUE TITLE
SIA 1.2.1 renter failure 

### ISSUE THREAD

**Issue by lasat** [NebulousLabs/Sia#1755]
Uploads fails with `Could not download file: download failed: insufficient hosts to recover file` and upload hung too.

```
goroutine 325 [running]:
runtime/debug.Stack(0x445747, 0x0, 0xc420479c28)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420479d80, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc4203d6280, 0xc420479d80, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc42094acc0, 0xc420479f20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5be
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc42094acc0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3ae
Critical error: ERROR: the renter is idle , but tracking active pieces: 1
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

OS: ubuntu 16.04

**Comment by lukechampine** [comment]
should be fixed in v1.3.0
