### ISSUE TITLE
 host crash 1.2.1 + missed proofs

### ISSUE THREAD

**Issue by chargr** [NebulousLabs/Sia#1780]
Sorry my scrollback in the screen session doesnt go far enough to get the full trace.

See a few similar to this:
```
goroutine 1757769 [runnable]:
syscall.Syscall6(0x12, 0x1f, 0xc42191a620, 0xe, 0x5ea92, 0x0, 0x0, 0xe, 0xe, 0x0)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pwrite(0x1f, 0xc42191a620, 0xe, 0xe, 0x5ea92, 0xc437c85c00, 0x7fbf990cbe10, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1389 +0x77
os.(*File).pwrite(0xc4203a60a8, 0xc42191a620, 0xe, 0xe, 0x5ea92, 0x9bb7c0, 0xc43645bc01, 0xc42191a620)
        /usr/lib/go/src/os/file_unix.go:212 +0x59
os.(*File).WriteAt(0xc4203a60a8, 0xc42191a620, 0xe, 0xe, 0x5ea92, 0xe, 0x3, 0x0)
        /usr/lib/go/src/os/file.go:166 +0xb3
github.com/NebulousLabs/Sia/modules/host/contractmanager.writeSectorMetadata(0xd96220, 0xc4203a60a8, 0x614a660000006c2f, 0x8f913ef0cc9c131a, 0xc428f80002, 0x0, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sector.go:103 +0x106
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).writeSectorMetadata(0xc4209840c8, 0xc420a4e420, 0x614a660031590002, 0x8f913ef0cc9c131a, 0xc400006c2f, 0xc433747e2c, 0xc43645be40)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:354 +0x77
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).managedRemoveSector(0xc4209840c8, 0xcc9c131a614a6600, 0xdcce78a68f913ef0, 0xe5c88e53dccf3a96, 0xaedab83cc3f848f5)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:323 +0x279
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).RemoveSectorBatch.func1(0xc420984000, 0xc4242a6200, 0x4ba8dd91eb8b78b8, 0xdcce78a619f51c4a, 0xe5c88e53dccf3a96, 0xaedab83cc3f848f5)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:480 +0xb9
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).RemoveSectorBatch
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:483 +0x196

```

And ends with:
```
goroutine 1730572 [runnable]:
github.com/NebulousLabs/bolt.(*Cursor).nsearch(0xc421482a40, 0xc421482c08, 0x20, 0x20)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:318 +0x1e4
github.com/NebulousLabs/bolt.(*Cursor).search(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x7681)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:263 +0x1fb
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x7fbe44b38000)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x4b38)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x7fbe476a5000)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x76a5)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x7fbeb92b0000)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x792b0)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc421482a40, 0xc421482c08, 0x20, 0x20, 0x0, 0x0, 0x2, 0x6, 0xc42494f680, 0x2, ...)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc42494e5c0, 0xc421482c08, 0x20, 0x20, 0x0, 0xc4215fb560, 0x2)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef
github.com/NebulousLabs/Sia/modules/consensus.validSiacoins(0xc423133960, 0xc423ef1500, 0x23, 0x23, 0xc42175e180, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:37 +0x18c
github.com/NebulousLabs/Sia/modules/consensus.validTransaction(0xc423133960, 0xc423ef1500, 0x23, 0x23, 0xc42175e180, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:297 +0xc5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).tryTransactionSet.func1(0xc423133960, 0xacba68, 0xc423133960)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:337 +0x13f
github.com/NebulousLabs/bolt.(*DB).Update(0xc420116780, 0xc425903198, 0x0, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/bolt/db.go:598 +0x9f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).tryTransactionSet(0xc420149b80, 0xc4201161e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:344 +0x150
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.tryTransactionSet)-fm(0xc4201161e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:92 +0x84
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).acceptTransactionSet(0xc42001a360, 0xc4201161e0, 0x2, 0x2, 0xc427a85b50, 0x0, 0x42acff)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:300 +0x581
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).AcceptTransactionSet.func1(0xc427a85b50, 0x0, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:341 +0xdb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).LockedTryTransactionSet(0xc420149b80, 0xc421233320, 0x0, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:385 +0x11b
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).AcceptTransactionSet(0xc42001a360, 0xc4201ea5a0, 0x2, 0x2, 0x1e8480, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:349 +0xeb
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).relayTransactionSet(0xc42001a360, 0xd96400, 0xc42b16f8c0, 0x0, 0x0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:376 +0x234
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).(github.com/NebulousLabs/Sia/modules/transactionpool.relayTransactionSet)-fm(0xd96400, 0xc42b16f8c0, 0x29, 0xc430c07f48)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:113 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedHandleConn(0xc42008cf20, 0xd96400, 0xc42b16f8c0)
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:213 +0x3c4
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer
        /home/chris/go-sia/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:173 +0x2ea
```

built with
```
GOOS=linux GOPATH=~/go-sia/ go build -ldflags "-s" -a -o ~/opt/sia-1.2.1/bin/siac ./siac
GOOS=linux GOPATH=~/go-sia/ go build -ldflags "-s" -a -o ~/opt/sia-1.2.1/bin/siad ./siad
```

launched with:
```
siad -M cghmrtw -d /data/sia/siad
```

I am running a host.

The end of my host log (including my recent start)
```
2017/05/07 22:04:11.779660 host.go:252: SHUTDOWN: Logging has terminated.
2017/05/07 22:49:31.688981 dependencies.go:105: STARTUP: Logging has started.
2017/05/07 22:50:48.946114 upnp.go:122: WARN: could not automatically forward port 9982: no UPnP-enabled gateway found
2017/05/07 22:50:48.946160 network.go:208: ERROR: failed to forward port: no UPnP-enabled gateway found
2017/05/08 01:20:50.327654 storageobligations.go:575: Missed storage proof. Revenue would have been 14973384071213846839126486460.
2017/05/08 01:21:13.693962 storageobligations.go:575: Missed storage proof. Revenue would have been 14953384071213846839126486460.
2017/05/08 11:59:32.027608 storageobligations.go:850: file contract complete, id 6e0017d8eee4db8babd7e6e4f64b26d80af53d5cb9b9620e645c1b021b84bd57
2017/05/09 02:49:52.383424 dependencies.go:105: STARTUP: Logging has started.
2017/05/09 02:50:05.841398 storageobligations.go:575: Missed storage proof. Revenue would have been 14953427851203654156343930300.
2017/05/09 02:51:19.533796 upnp.go:122: WARN: could not automatically forward port 9982: no UPnP-enabled gateway found
2017/05/09 02:51:19.533832 network.go:208: ERROR: failed to forward port: no UPnP-enabled gateway found
```

I am not sure why storage proofs were missed (host was up).

**Comment by chargr** [comment]
This looks like a duplicate of:
https://github.com/NebulousLabs/Sia/issues/1775
