### ISSUE TITLE
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system

### ISSUE THREAD

**Issue by franzos** [NebulousLabs/Sia#1790]
macOS 10.12.4, Sia version 1.2.1

```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.077420784 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420b475f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420b47948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd14, 0xe, 0x7fff5fbffd40, 0x5, 0x7fff5fbffd2f, 0x5, 0x0, 0x7fff5fbffd50, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420089200, 0xc420019540, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420089200, 0xc42000e0d0, 0x5, 0x5, 0xc420089200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0xc420089200, 0x16c6004, 0x3b, 0xc42015a820)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420089200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...
Shutdown complete.
```

This happened pretty much overnight. 
1) Transferred SC to Sia
2) Created Allowance (1 TB)
3) Left at creating contracts ... this is where it must have happen

**Comment by DavidVorick** [comment]
Were you running the UI? There is a known (and fixed but not yet released) issue with the UI that causes this issue. Release in a week or so

**Comment by franzos** [comment]
@DavidVorick indeed! Glad this has been fixed.
