### ISSUE TITLE
Siad crash while trying to copy in-use files on Windows

### ISSUE THREAD

**Issue by sgraves66** [NebulousLabs/Sia#1844]
Using siad v1.2.2

I have online backup running in background. I'm excluding .log/.json as a workaround, but it's typically best to retry a few times after failure (with a delay between) on Windows for critical file operations.

```
goroutine 102570 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04221fdc8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04221ff20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042175de0, 0xc04221ff20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc042350720, 0xc042070668)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:51 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
goroutine 107789 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc0468b1dc8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0468b1f20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042175de0, 0xc0468b1f20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0454b3b70, 0xc042070668)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:51 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
goroutine 112435 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc046be5dc8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc046be5f20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042175de0, 0xc046be5f20, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc042225510, 0xc042070668)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:51 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
```

**Comment by DavidVorick** [comment]
This is a known bug. It's not a crash unless you are running the debugging build, the general releases will print this info but keep running like normal.

I'm working on an update to the contract manager to address this. It's pretty far down the pipeline though, right now we're entirely focused on:

+ fixing the wallet
+ enabling the auto-repair stuff in the renter.

**Comment by sgraves66** [comment]
Thanks. Should close this or leave for tracking? I skimmed through issues but didn't find a duplicate. Sounds like it's covered either way.

**Comment by tbenz9** [comment]
Recommendation to devs: Close
