### ISSUE TITLE
Sia-UI and Siad exited unexpectedly

### ISSUE THREAD

**Issue by Aquilae32** [NebulousLabs/Sia#1939]
I use a macOS computer with a Raid 0 Thunderbolt drive.

While creating allowance, Sia-UI and Said exited unexpectedly. Here are the logs:

**Error Log on Sia-UI**:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.556823642 seconds
Closing renter...
Closing host...

**

**Error Log on Siad**:

[My_computer_ID]$ ./siad --sia-directory /Volumes/G-RAID_Thunderbolt/Mes_applications/Sia
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 22.654321627 seconds
Wallet: scanned to height 109519...
Done!

**[I started the creation of allowance and left for the day. When I returned, there was the following]**

goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4213915f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc421391948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x16ac1fe, 0xe, 0x169b7b8, 0x5, 0x169b7bd, 0x5, 0x0, 0x169e154, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc42007f200, 0xc4200bf7a0, 0x0, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc42007f200, 0xc42000e190, 0x2, 0x2, 0xc42007f200, 0xc42000e190)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42007f200, 0x16c7c0f, 0x3b, 0xc42014e8c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42007f200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...

**Comment by Aquilae32** [comment]
After that I decided to upload a file of 22 Go with many repertories and Sia crashed again:

**Error log**

2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 160ms
2017/06/15 22:04:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 320ms
2017/06/15 22:04:05 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 640ms
2017/06/15 22:04:05 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 160ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 160ms
2017/06/15 22:04:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 320ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 160ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/15 22:04:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
goroutine 238728 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc421047c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421047e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42016c100, 0xc421047e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc42210eec0, 0xc4201ba428, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-aheagoroutine 238727 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc420ee2d68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc420ee2ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42016c100, 0xc420ee2ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc42210eec0, 0xc4201ba428)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
d-log: open /Volumes/G-RAID_Thunderbolt/Mes_applications/Sia/host/contractmanager/contractmanager.wal_temp: too many open files
Severe error: Unable to open temporary settings file for writing: open /Volumes/G-RAID_Thunderbolt/Mes_applications/Sia/host/contractmanager/contractmanager.json_temp: too many open files
goroutine 238728 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc421047c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421047e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42016c100, 0xc421047e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc42210eec0, 0xc4201ba428, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 238728 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc421047aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421047c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42016c100, 0xc421047c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4201ba428, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc42210eec0, 0xc4201ba428, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 238728 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4201ba428, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc42210eec0, 0xc4201ba428, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by Aquilae32** [comment]
It happened again while updating the blockchain.

[My computer ID]:~ louis$ cd /Applications/Sia-v1.2.2-darwin-amd64
[My computer ID]:Sia-v1.2.2-darwin-amd64 louis$ ./siad --sia-directory /Volumes/G-RAID_Thunderbolt/Mes_applications/Sia
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.298136739 seconds
Wallet: scanned to height 109927...
Done!
2017/06/17 23:56:47 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:56:47 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:56:50 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:56:50 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:56:51 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:56:51 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/06/17 23:56:51 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/06/17 23:56:51 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms
2017/06/17 23:56:51 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 80ms
2017/06/17 23:56:52 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 160ms
2017/06/17 23:56:52 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 320ms
2017/06/17 23:56:53 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 640ms
2017/06/17 23:56:53 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:54 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:55 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:56 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:57 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:58 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:56:59 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:00 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:01 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:02 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:03 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:04 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:05 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:06 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:07 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 1s
2017/06/17 23:57:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/06/17 23:57:08 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
goroutine 18482 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc4210b0c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4210b0e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201d4ba0, 0xc4210b0e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4218e0fd0, 0xc420320548, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /Volumes/G-RAID_Thunderbolt/Mes_applications/Sia/host/contractmanager/contractmanager.wal_temp: too many open files
goroutine 18482 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc4210b0c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4210b0e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201d4ba0, 0xc4210b0e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4218e0fd0, 0xc420320548, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 18482 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc4210b0aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4210b0c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201d4ba0, 0xc4210b0c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420320548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4218e0fd0, 0xc420320548, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 18482 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420320548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4218e0fd0, 0xc420320548, 0x0, 0x0, 0x0, 0x1ac2e18, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by Aquilae32** [comment]
This issue was fixed using this : https://github.com/NebulousLabs/Sia/issues/1840.

I have to say that even with this solution, the directory selection stopped halfway (after selecting half of the directories targeted). Sia-UI indicated something like "socket timed out" several times. I will try to add the missing directories ounce uploading is complete.
