### ISSUE TITLE
storage obligation is unlocked, and should not be getting unlocked

### ISSUE THREAD

**Issue by S-anasol** [NebulousLabs/Sia#1956]
`goroutine 18443 [running]:
runtime/debug.Stack(0x445687, 0x0, 0xc421e24d00)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc421e24e28, 0x1, 0x1)
	/root/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc4200b8920, 0xc421e24e28, 0x1, 0x1)
	/root/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/host.(*Host).managedUnlockStorageObligation(0xc420148580, 0x234c00e6be05221a, 0xd18fd73b7e9e21c6, 0xee0dbe73b3e4344c, 0xdb2a8aedaf05b6ac)
	/root/go/src/github.com/NebulousLabs/Sia/modules/host/storageobligationslock.go:64 +0x102
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract.func1(0xc420148580, 0xc421e256a8)
	/root/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:87 +0xa9
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc420148580, 0xdbc160, 0xc4202140a0, 0xdb1ba0, 0xc420aa5000)
	/root/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:192 +0x1445
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc420148580, 0xdbc160, 0xc4202140a0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x6c1
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
	/root/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:332 +0xc3
Critical error: storage obligation is unlocked, and should not be getting unlocked
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues`

One of hosts got this error in few minutes after start.
After error `siac host` command and host stop working.

![image](https://user-images.githubusercontent.com/1709666/27263940-6bdcb9de-547d-11e7-842e-49a7b8dfc1c3.png)

**Comment by S-anasol** [comment]
built from [release sources Sia v1.2.2](https://github.com/NebulousLabs/Sia/releases)
problem has gone...
