### ISSUE TITLE
Submitting bug report

### ISSUE THREAD

**Issue by damiendonnelly** [NebulousLabs/Sia#1957]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.133126845 seconds

Wallet: scanned to height 37114...
Wallet: scanned to height 37328...
Wallet: scanned to height 37532...
Wallet: scanned to height 37715...
Wallet: scanned to height 38002...
Wallet: scanned to height 38270...
Wallet: scanned to height 38492...
Wallet: scanned to height 38615...
Wallet: scanned to height 38739...
Wallet: scanned to height 38929...
Wallet: scanned to height 39208...
Wallet: scanned to height 39346...
Wallet: scanned to height 39490...
Wallet: scanned to height 39630...
Wallet: scanned to height 39810...
Wallet: scanned to height 40029...
Wallet: scanned to height 40258...
Wallet: scanned to height 40519...
Wallet: scanned to height 40784...
Wallet: scanned to height 41196...
Wallet: scanned to height 41603...
Wallet: scanned to height 41719...
Wallet: scanned to height 41875...
Wallet: scanned to height 42067...
Wallet: scanned to height 42240...
Wallet: scanned to height 42419...
Wallet: scanned to height 42961...
Wallet: scanned to height 43416...
Wallet: scanned to height 43703...
Wallet: scanned to height 43915...
Wallet: scanned to height 44254...
Wallet: scanned to height 44353...
Wallet: scanned to height 44453...
Wallet: scanned to height 44577...
Wallet: scanned to height 44664...
Wallet: scanned to height 44818...
Wallet: scanned to height 44915...
Wallet: scanned to height 45015...
Wallet: scanned to height 45111...
Wallet: scanned to height 45263...
Wallet: scanned to height 45384...
Wallet: scanned to height 45515...
Wallet: scanned to height 45636...
Wallet: scanned to height 45806...
Wallet: scanned to height 45992...
Wallet: scanned to height 46174...
Wallet: scanned to height 46544...
Wallet: scanned to height 46848...
Wallet: scanned to height 47081...
Wallet: scanned to height 47282...
Wallet: scanned to height 47516...
Wallet: scanned to height 47619...
Wallet: scanned to height 47839...
Wallet: scanned to height 48208...
Wallet: scanned to height 48525...
Wallet: scanned to height 48910...
Wallet: scanned to height 49343...
Wallet: scanned to height 49684...
Wallet: scanned to height 50246...
Wallet: scanned to height 50604...
Wallet: scanned to height 50946...
Wallet: scanned to height 51278...
Wallet: scanned to height 51674...
Wallet: scanned to height 52243...
Wallet: scanned to height 52937...
Wallet: scanned to height 53119...
Wallet: scanned to height 53224...
Wallet: scanned to height 53332...
Wallet: scanned to height 53413...
Wallet: scanned to height 53519...
Wallet: scanned to height 53623...
Wallet: scanned to height 53746...
Wallet: scanned to height 53843...
Wallet: scanned to height 54003...
Wallet: scanned to height 54138...
Wallet: scanned to height 54246...
Wallet: scanned to height 54406...
Wallet: scanned to height 54552...
Wallet: scanned to height 54772...
Wallet: scanned to height 54963...
Wallet: scanned to height 55347...
Wallet: scanned to height 55791...
Wallet: scanned to height 56128...
Wallet: scanned to height 56346...
Wallet: scanned to height 56471...
Wallet: scanned to height 56873...
Wallet: scanned to height 56978...
Wallet: scanned to height 57661...
Wallet: scanned to height 58029...
Wallet: scanned to height 58447...
Wallet: scanned to height 59402...
Wallet: scanned to height 60099...
Wallet: scanned to height 60431...
Wallet: scanned to height 60714...
Wallet: scanned to height 61024...
Wallet: scanned to height 61383...
Wallet: scanned to height 61684...
Wallet: scanned to height 61988...
Wallet: scanned to height 62245...
Wallet: scanned to height 62545...
Wallet: scanned to height 62861...
Wallet: scanned to height 63141...
Wallet: scanned to height 63441...
Wallet: scanned to height 63717...
Wallet: scanned to height 64004...
Wallet: scanned to height 64215...
Wallet: scanned to height 64318...
Wallet: scanned to height 64445...
Wallet: scanned to height 64615...
Wallet: scanned to height 64836...
Wallet: scanned to height 65080...
Wallet: scanned to height 65328...
Wallet: scanned to height 65621...
Wallet: scanned to height 65844...
Wallet: scanned to height 66141...
Wallet: scanned to height 66407...
Wallet: scanned to height 66731...
Wallet: scanned to height 67067...
Wallet: scanned to height 67398...
Wallet: scanned to height 67717...
Wallet: scanned to height 67992...
Wallet: scanned to height 68306...
Wallet: scanned to height 68589...
Wallet: scanned to height 68857...
Wallet: scanned to height 69092...
Wallet: scanned to height 69392...
Wallet: scanned to height 69733...
Wallet: scanned to height 70023...
Wallet: scanned to height 70260...
Wallet: scanned to height 70507...
Wallet: scanned to height 70751...
Wallet: scanned to height 71034...
Wallet: scanned to height 71274...
Wallet: scanned to height 71497...
Wallet: scanned to height 71714...
Wallet: scanned to height 71960...
Wallet: scanned to height 72205...
Wallet: scanned to height 72449...
Wallet: scanned to height 72698...
Wallet: scanned to height 72986...
Wallet: scanned to height 73231...
Wallet: scanned to height 73477...
Wallet: scanned to height 73716...
Wallet: scanned to height 73941...
Wallet: scanned to height 74208...
Wallet: scanned to height 74499...
Wallet: scanned to height 74768...
Wallet: scanned to height 75023...
Wallet: scanned to height 75257...
Wallet: scanned to height 75424...
Wallet: scanned to height 75632...
Wallet: scanned to height 75836...
Wallet: scanned to height 76099...
Wallet: scanned to height 76309...
Wallet: scanned to height 76534...
Wallet: scanned to height 76792...
Wallet: scanned to height 77016...
Wallet: scanned to height 77324...
Wallet: scanned to height 77598...
Wallet: scanned to height 77948...
Wallet: scanned to height 78249...
Wallet: scanned to height 78569...
Wallet: scanned to height 78872...
Wallet: scanned to height 79140...
Wallet: scanned to height 79431...
Wallet: scanned to height 79701...
Wallet: scanned to height 79969...
Wallet: scanned to height 80294...
Wallet: scanned to height 80587...
Wallet: scanned to height 80907...
Wallet: scanned to height 81252...
Wallet: scanned to height 81583...
Wallet: scanned to height 81946...
Wallet: scanned to height 82255...
Wallet: scanned to height 82558...
Wallet: scanned to height 82907...
Wallet: scanned to height 83244...
Wallet: scanned to height 83540...
Wallet: scanned to height 83855...
Wallet: scanned to height 84169...
Wallet: scanned to height 84527...
Wallet: scanned to height 84846...
Wallet: scanned to height 85187...
Wallet: scanned to height 85535...
Wallet: scanned to height 85921...
Wallet: scanned to height 86280...
Wallet: scanned to height 86557...
Wallet: scanned to height 86825...
Wallet: scanned to height 87111...
Wallet: scanned to height 87427...
Wallet: scanned to height 87695...
Wallet: scanned to height 87946...
Wallet: scanned to height 88203...
Wallet: scanned to height 88482...
Wallet: scanned to height 88821...
Wallet: scanned to height 89117...
Wallet: scanned to height 89393...
Wallet: scanned to height 89732...
Wallet: scanned to height 90012...
Wallet: scanned to height 90341...
Wallet: scanned to height 90659...
Wallet: scanned to height 90966...
Wallet: scanned to height 91289...
Wallet: scanned to height 91605...
Wallet: scanned to height 91894...
Wallet: scanned to height 92198...
Wallet: scanned to height 92473...
Wallet: scanned to height 92761...
Wallet: scanned to height 93052...
Wallet: scanned to height 93397...
Wallet: scanned to height 93674...
Wallet: scanned to height 93989...
Wallet: scanned to height 94293...
Wallet: scanned to height 94560...
Wallet: scanned to height 94856...
Wallet: scanned to height 95115...
Wallet: scanned to height 95425...
Wallet: scanned to height 95742...
Wallet: scanned to height 96033...
Wallet: scanned to height 96321...
Wallet: scanned to height 96637...
Wallet: scanned to height 96877...
Wallet: scanned to height 97176...
Wallet: scanned to height 97492...
Wallet: scanned to height 97785...
Wallet: scanned to height 98065...
Wallet: scanned to height 98377...
Wallet: scanned to height 98646...
Wallet: scanned to height 98892...
Wallet: scanned to height 99181...
Wallet: scanned to height 99450...
Wallet: scanned to height 99661...
Wallet: scanned to height 99848...
Wallet: scanned to height 100042...
Wallet: scanned to height 100239...
Wallet: scanned to height 100474...
Wallet: scanned to height 100652...
Wallet: scanned to height 100852...
Wallet: scanned to height 101092...
Wallet: scanned to height 101294...
Wallet: scanned to height 101511...
Wallet: scanned to height 101692...
Wallet: scanned to height 101900...
Wallet: scanned to height 102062...
Wallet: scanned to height 102260...
Wallet: scanned to height 102457...
Wallet: scanned to height 102646...
Wallet: scanned to height 102854...
Wallet: scanned to height 103055...
Wallet: scanned to height 103242...
Wallet: scanned to height 103421...
Wallet: scanned to height 103623...
Wallet: scanned to height 103815...
Wallet: scanned to height 103989...
Wallet: scanned to height 104188...
Wallet: scanned to height 104397...
Wallet: scanned to height 104585...
Wallet: scanned to height 104830...
Wallet: scanned to height 105098...
Wallet: scanned to height 105345...
Wallet: scanned to height 105600...
Wallet: scanned to height 105866...
Wallet: scanned to height 106105...
Wallet: scanned to height 106337...
Wallet: scanned to height 106613...
Wallet: scanned to height 106863...
Wallet: scanned to height 107085...
Wallet: scanned to height 107324...
Wallet: scanned to height 107548...
Wallet: scanned to height 107757...
Wallet: scanned to height 107948...
Wallet: scanned to height 108188...
Wallet: scanned to height 108427...
Wallet: scanned to height 108646...
Wallet: scanned to height 108858...
Wallet: scanned to height 109018...
Wallet: scanned to height 109185...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4200335f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420033948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcc4, 0xe, 0x7fff5fbffcf0, 0x5, 0x7fff5fbffcdf, 0x5, 0x0, 0x7fff5fbffd46, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420097200, 0xc4200991d0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420097200, 0xc42006c070, 0x5, 0x5, 0xc420097200, 0xc42006c070)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420097200, 0x16c7c0f, 0x3b, 0xc4201688c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420097200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by S-anasol** [comment]
> Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system

just increase limits

https://stackoverflow.com/a/923369

**Comment by damiendonnelly** [comment]
Thanks
