### ISSUE TITLE
Critical error: entry does not exist

### ISSUE THREAD

**Issue by TimonPeng** [NebulousLabs/Sia#2074]
```
$ siad -d --api-addr=localhost:9980 --rpc-addr=:9981 -M 'ecg'
Loading...
(0/3) Loading siad...
(1/3) Loading gateway...
(2/3) Loading consensus...
(3/3) Loading explorer...
Finished loading in 0.029624762 seconds
goroutine 10239 [running]:
runtime/debug.Stack(0x1045737, 0x0, 0xc422e93540)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc422e935c8, 0x1, 0x1)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).LatestBlockFacts(0xc420172840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/modules/explorer/info.go:51 +0xf3
github.com/NebulousLabs/Sia/api.(*API).explorerHandler(0xc42021a120, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/api/explorer.go:356 +0x4c
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.explorerHandler)-fm(0x19c6fc0, 0xc4216cf500, 0xc42000ad00, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/api/api.go:169 +0x66
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420014340, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/src/github.com/julienschmidt/httprouter/router.go:344 +0x813
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/api/api.go:98 +0xba
net/http.HandlerFunc.ServeHTTP(0xc42001b260, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1942 +0x44
github.com/NebulousLabs/Sia/api.(*API).ServeHTTP(0xc42021a120, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/src/github.com/NebulousLabs/Sia/api/api.go:138 +0x58
net/http.(*ServeMux).ServeHTTP(0xc4200edc80, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42001ef20, 0x19c6fc0, 0xc4216cf500, 0xc42000ad00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4212b8280, 0x19c7940, 0xc42035f480)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
Critical error: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

**Comment by tbenz9** [comment]
Recommendation to Devs: "Bug"

@lukechampine This bug has appeared a few times as well, might be worth looking into.

**Comment by lukechampine** [comment]
The explorer is in a state of disrepair right now, and will likely be replace wholesale at this point.
