### ISSUE TITLE
Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by poiuty** [NebulousLabs/Sia#2106]
Send 1000 txs.
```
<?php 
for($i=0;$i<1000;$i++) {
$address = `siac wallet address`;

echo $address.PHP_EOL;

$clean_addr = trim(str_replace("Created new address: ", "", $address));
echo $clean_addr.PHP_EOL;

$send = `siac wallet send siacoins 1pS {$clean_addr}`;

echo $send.PHP_EOL;
}
```

Check balance.

```
# siac wallet
goroutine 1 [running]:
runtime/debug.Stack(0x443fe7, 0x0, 0xc42009b410)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42009b4b8, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/types.Currency.Sub(0x82b000, 0xc4201401c0, 0x2, 0x7, 0x0, 0xc4201482d0, 0x2, 0x5, 0x0, 0xc4201401c0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x15d
main.walletbalancecmd()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siac/walletcmd.go:361 +0x248
reflect.Value.call(0x79c620, 0x848620, 0x13, 0x828e70, 0x4, 0xa46220, 0x0, 0x0, 0x410b28, 0x10, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x79c620, 0x848620, 0x13, 0xa46220, 0x0, 0x0, 0xc42009baf0, 0x531d14, 0xc420080d20)
	/usr/local/go/src/reflect/value.go:302 +0xa4
main.wrap.func1(0xa23440, 0xa46220, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siac/main.go:223 +0x1c7
github.com/spf13/cobra.(*Command).execute(0xa23440, 0xa46220, 0x0, 0x0, 0xa23440, 0xa46220)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008cd80, 0x1, 0x843813, 0x4d)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008cd80, 0xa285d0, 0x8290ac)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siac/main.go:302 +0xf88
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   576.7 SC
Unconfirmed Delta:  +8.054 KS
Exact:               576687252578112589099326487 H
Siafunds:            0 SF
Siafund Claims:      0 H
```

**Comment by lukechampine** [comment]
this should no longer happen. Please reopen if this happens with v1.3.0
