### ISSUE TITLE
got panic of explorer modules 

### ISSUE THREAD

**Issue by LgxAtGitHub** [NebulousLabs/Sia#2182]
It is seem there have some wrong about explorer moudle.

I started said with ```./siad --modules cgmhrtwe --modules cgmhrtwe```
it stay at step 3 long time, and got panic many times
```
Loading...
(0/8) Loading siad...
(1/8) Loading gateway...
(2/8) Loading consensus...
(3/8) Loading explorer...
(4/8) Loading transaction pool...
(5/8) Loading wallet...
(6/8) Loading miner...
(7/8) Loading host...
(8/8) Loading renter...
Finished loading in 127.546130579 seconds
goroutine 15 [running]:
runtime/debug.Stack(0x445687, 0x0, 0xc420c14d70)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420c14e48, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc4201886f0, 0xdbf9890adc750e21, 0x72f9d606d1a9fe22, 0xe9817ccac33661a0, 0x9b03d24f9c0e9af2, 0x0, 0x0, 0x0, 0xc4203c4060, 0x1, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:270 +0x15a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc42013db80, 0x0, 0x0, 0x0, 0xc423b678a0, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:114 +0x173
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc42013db80, 0x4839010000000000, 0x2c6716bc114f0fb7, 0x3a7b89b2887798bb, 0x7eabe1cb4cf5c07b, 0x1fbaef3f, 0x56ba6c93, 0xc426a8b9c0, 0x1, 0x1, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:278 +0x1e9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc42013db80, 0xd993c0, 0xc42075e020, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:194 +0x521
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xd993c0, 0xc42075e020, 0x9fa780, 0xc4201a60b0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:411 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200791e0, 0xc420187460, 0x11, 0xaa232c, 0xa, 0xc4201a6050, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:57 +0x25f
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200791e0, 0xc420187460, 0x11, 0xaa232c, 0xa, 0xc4201a6050, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:67 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc42013db80, 0xc420c15ef0, 0xc420c15eb0, 0xc420c15eb8, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:554 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc42013db80, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x307
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420288570, 0xc42013db80, 0xd99640, 0xc4200791e0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
.
```

And when I press ctrl-c, I got same panic many times too.

**Comment by S-anasol** [comment]
https://github.com/NebulousLabs/Sia/issues/2181#issuecomment-317549364

https://github.com/NebulousLabs/Sia/issues/1990

**Comment by tbenz9** [comment]
Looks like this is being tracked in issues linked above.

Recommendation to devs: Close

**Comment by tbenz9** [comment]
Duplicate of #2074
