### ISSUE TITLE
Sia UI 1.3.0 Crash Report

### ISSUE THREAD

**Issue by Johnb21** [NebulousLabs/Sia#2203]
I was trying to use Sia UI 1.3.0 (upgrading from 1.2) on Windows and got the following error dump:

```Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.6097361 seconds
panic: runtime error: slice bounds out of range

goroutine 32 [running]:
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).getBlockTotals(0xc042127b80, 0xc0430ea460, 0x2600000000000000, 0x9ac9d3452a4b72a9, 0xfcd9818037fb712b, 0xeb2f4717101d695e, 0xc043fc0540, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:120 +0x13b
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).newChild(0xc042127b80, 0xc0430ea460, 0xc042179760, 0x2600000000000000, 0x9ac9d3452a4b72a9, 0xfcd9818037fb712b, 0xeb2f4717101d695e, 0x680a79026dd2e0, 0x597906fd, 0xc043fc0540, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/processedblock.go:135 +0x1a8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042127b80, 0xc0430ea460, 0x2600000000000000, 0x9ac9d3452a4b72a9, 0xfcd9818037fb712b, 0xeb2f4717101d695e, 0x680a79026dd2e0, 0x597906fd, 0xc043fc0540, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:151 +0xa3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0430ea460, 0xb0b570, 0xc0430ea460)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420f4780, 0xc0420292e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042127b80, 0xc04202f000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042127b80, 0xde41c0, 0xc04203c240, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc04203c240, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042068c60, 0xc042199580, 0x13, 0xaddb78, 0xa, 0xc042036220, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042068c60, 0xc042199580, 0x13, 0xaddb78, 0xa, 0xc042036220, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042127b80, 0xc042029ef0, 0xc042029eb0, 0xc042029eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042127b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04222e960, 0xc042127b80, 0xde4440, 0xc042068c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641```

**Comment by Johnb21** [comment]
Now I cannot open 1.2 without getting the same error dump

**Comment by Johnb21** [comment]
Closing. I saw this has already been discussed here: https://github.com/NebulousLabs/Sia/issues/2183

I will delete the consensus file and see if that solves the issue
