### ISSUE TITLE
Error on starting sia ui

### ISSUE THREAD

**Issue by bao-minted** [NebulousLabs/Sia#2220]
I'm getting this error on starting sia ui

```
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
unexpected fault address 0x856fd03008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x856fd03008 pc=0x132d3c9]

goroutine 1 [running]:
runtime.throw(0x16d0af7, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x421df3c38 sp=0x421df3c18
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0x1c8 fp=0x421df3c88 sp=0x421df3c38
github.com/NebulousLabs/bolt.(*Cursor).search(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x14dec6)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:255 +0x69 fp=0x421df3d50 sp=0x421df3c88
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x84a8caa000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0x421df3de0 sp=0x421df3d50
github.com/NebulousLabs/bolt.(*Cursor).search(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x86e6d)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0x421df3ea8 sp=0x421df3de0
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x84272ba000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0x421df3f38 sp=0x421df3ea8
github.com/NebulousLabs/bolt.(*Cursor).search(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x547d)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0x421df4000 sp=0x421df3f38
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x842732f000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0x421df4090 sp=0x421df4000
github.com/NebulousLabs/bolt.(*Cursor).search(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x54f2)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0x421df4158 sp=0x421df4090
github.com/NebulousLabs/bolt.(*Cursor).seek(0x421df4218, 0x421df42b8, 0x20, 0x20, 0x0, 0x0, 0x12de7c3, 0x421d242b8, 0x4233606c0, 0x3, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1 fp=0x421df41a8 sp=0x421df4158
github.com/NebulousLabs/bolt.(*Bucket).Get(0x42488c800, 0x421df42b8, 0x20, 0x20, 0x42488c800, 0x1cebbadea7f679a2, 0x3e22e7cb8a879244)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef fp=0x421df4248 sp=0x421df41a8
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0x421d242a0, 0x1000000000000000, 0xe73f0676b116a129, 0x5d2ed26d92d8419a, 0xfb7b16a313de8d4f, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:185 +0x7d fp=0x421df42b0 sp=0x421df4248
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0x421d59b80, 0x421d242a0, 0x0, 0x0, 0x0, 0x4249b5820, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x818 fp=0x421df4eb0 sp=0x421df42b0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0x421d242a0, 0x17081f0, 0x421d242a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0 fp=0x421df5190 sp=0x421df4eb0
github.com/NebulousLabs/bolt.(*DB).View(0x421d26780, 0x421ca7248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f fp=0x421df51e0 sp=0x421df5190
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0x421d59b80, 0x19deca0, 0x4220d8000, 0xaf6a190c2604bf26, 0x8397d94b61e9eee0, 0x92ae1dc583e9fd1c, 0x673a70232a2844f6, 0x14d33c7, 0x85b7009115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f fp=0x421df52c8 sp=0x421df51e0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0x421d59b80, 0x19deca0, 0x4220d8000, 0xaf6a190c2604bf26, 0x8397d94b61e9eee0, 0x92ae1dc583e9fd1c, 0x673a70232a2844f6, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee fp=0x421df5370 sp=0x421df52c8
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0x4220d8000, 0x421f160f0, 0x421f0a1e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x944 fp=0x421df55a8 sp=0x421df5370
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19ea7c0, 0x421d59b80, 0x19e9ba0, 0x421c88c60, 0x421f160f0, 0x47, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276 fp=0x421df5620 sp=0x421df55a8
main.startDaemon(0x0, 0x0, 0x7fff5fbffd2c, 0xe, 0x7fff5fbffd58, 0x5, 0x7fff5fbffd47, 0x5, 0x0, 0x7fff5fbffdb0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x1693 fp=0x421df5bd0 sp=0x421df5620
main.startDaemonCmd(0x421c91200, 0x421c93360, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162 fp=0x421df5cd0 sp=0x421df5bd0
github.com/spf13/cobra.(*Command).execute(0x421c91200, 0x421c6a070, 0x5, 0x5, 0x421c91200, 0x421c6a070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299 fp=0x421df5d88 sp=0x421df5cd0
github.com/spf13/cobra.(*Command).ExecuteC(0x421c91200, 0x16fce88, 0x3b, 0x421d6a8c0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339 fp=0x421df5ed8 sp=0x421df5d88
github.com/spf13/cobra.(*Command).Execute(0x421c91200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b fp=0x421df5f08 sp=0x421df5ed8
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa fp=0x421df5f88 sp=0x421df5f08
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0x421df5fe0 sp=0x421df5f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0x421df5fe8 sp=0x421df5fe0

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [IO wait]:
net.runtime_pollWait(0x8421c6a130, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0x421d68ca8, 0x72, 0x0, 0x42400e040)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0x421d68ca8, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0x421d68c40, 0x0, 0x19dffe0, 0x42400e040)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0x421c78128, 0x421eafe70, 0x129d31e, 0x1054480)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0x421c78128, 0x1708860, 0x421ce45a0, 0x19e6be0, 0x421c10150)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0x421caed10, 0x19e5f20, 0x421c78128, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
main.(*Server).Serve(0x421cd38c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/server.go:416 +0x44
main.startDaemon.func1(0x421d701e0, 0x421cd38c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:145 +0x2b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:146 +0x312

goroutine 20 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedSaveLoop(0x421c88c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/persist.go:57 +0x122
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:249 +0x683

goroutine 21 [IO wait]:
net.runtime_pollWait(0x8421c6a070, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0x421d68ed8, 0x72, 0x0, 0x421ebe000)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0x421d68ed8, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0x421d68e70, 0x0, 0x19dffe0, 0x421ebe000)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0x421c78158, 0x400000008, 0x421eba000, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0x421c78158, 0x1708c50, 0x421d702a0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentListen(0x421c88c60, 0x421d702a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:99 +0x75
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:294 +0xa23

goroutine 22 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedSleep(0x421c88c60, 0x12a05f200, 0x421e54000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:164 +0x121
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager(0x421c88c60, 0x421d70300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:153 +0x608
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:301 +0xacf

goroutine 23 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodeManager(0x421c88c60, 0x421d70360)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:283 +0x5e0
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:308 +0xb7b

goroutine 24 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodePurger(0x421c88c60, 0x421d703c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:221 +0x650
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:315 +0xc27

goroutine 25 [IO wait]:
net.runtime_pollWait(0x8421c69ef0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0x423202068, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0x423202068, 0x421d2c800, 0x800)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).readFrom(0x423202000, 0x421d2c800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_unix.go:277 +0x1cc
net.(*UDPConn).readFrom(0x421c780e0, 0x421d2c800, 0x800, 0x800, 0x421e41730, 0x103fb7b, 0x800, 0x15ed9c0)
	/usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0x421c780e0, 0x421d2c800, 0x800, 0x800, 0x800, 0x800, 0x85, 0x0, 0x0)
	/usr/local/go/src/net/udpsock.go:109 +0x75
github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0x422878020, 0x421cde300, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/httpu/httpu.go:91 +0x54f
github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/ssdp.SSDPRawSearch(0x422878020, 0x16f8230, 0x2f, 0x2, 0x3, 0xe0cedf15a54a4c5a, 0xb42cdd7d7f5aef1d, 0x6fc8c32a4cc53590, 0xcd28dd8a2d245131, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/ssdp/ssdp.go:52 +0x607
github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp.DiscoverDevices(0x16f8230, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/goupnp.go:66 +0xf1
github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp.NewServiceClients(0x16f8230, 0x2f, 0x1aef5a0, 0x16d1353, 0x5, 0x13, 0x2, 0x421eace30, 0x10473b9, 0x1aef5a0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/service_client.go:27 +0x4d
github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/dcps/internetgateway1.NewWANPPPConnection1Clients(0x1908b100, 0x1a4, 0x421e2c690, 0x0, 0x421e24000, 0x421e2c6b0, 0x102864e, 0x400000008)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/vendor/github.com/huin/goupnp/dcps/internetgateway1/internetgateway1.go:2860 +0x3d
github.com/NebulousLabs/go-upnp.Discover(0x400000008, 0x17081b0, 0x421c88d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:130 +0x5a
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedForwardPort(0x421c88c60, 0x421d5aec5, 0x4)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:97 +0x8b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:318 +0xc5e

goroutine 26 [sleep]:
time.Sleep(0x54296900)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/go-upnp.Discover(0x400000008, 0x17081b0, 0x421c88d48)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:129 +0x55
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedLearnHostname(0x421c88c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:59 +0x8e
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:319 +0xc83

goroutine 34 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer.func1(0x421e79860, 0x421c88c60, 0x421e798c0, 0x422451b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:153 +0x1b7
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:163 +0x10a

goroutine 57 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0x421d59b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:623 +0x1e2
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0x421f02cf0, 0x421d59b80, 0x19e9ba0, 0x421c88c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a

goroutine 29 [select]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0x4220d8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:38 +0x198
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3ef

goroutine 67 [semacquire]:
sync.runtime_notifyListWait(0x4232ea010, 0x0)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0x4232ea000)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/NebulousLabs/muxado/proto/buffer.(*Inbound).Read(0x4232ee000, 0x4232f6000, 0x4, 0x4, 0x8421c7aef8, 0x10520e0, 0x1af4390)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/buffer/inbound.go:155 +0x173
github.com/NebulousLabs/muxado/proto.(*Stream).Read(0x4232f2000, 0x4232f6000, 0x4, 0x4, 0x2, 0x8421bfd4b0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/stream.go:73 +0x57
io.ReadAtLeast(0x8421c7aef8, 0x4232f2000, 0x4232f6000, 0x4, 0x4, 0x4, 0x16b2a60, 0x19eaa00, 0x8421c7aef8)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x8421c7aef8, 0x4232f2000, 0x4232f6000, 0x4, 0x4, 0x4, 0x0, 0x4220085a0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).respond(0x4236f4180)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:81 +0x11a
created by github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).Start
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:46 +0x7d

goroutine 68 [sleep]:
time.Sleep(0xb2d05e00)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).request(0x4236f4180)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:107 +0xc6
created by github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).Start
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:47 +0x9f

goroutine 69 [select]:
github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).check(0x4236f4180)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:57 +0x13a
created by github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).Start
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:48 +0xc1

goroutine 70 [IO wait]:
net.runtime_pollWait(0x8421c69fb0, 0x72, 0xa)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0x421f12068, 0x72, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0x421f12068, 0x422aaa1a8, 0x8)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0x421f12000, 0x422aaa1a8, 0x8, 0x8, 0x0, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0x4220cc0f0, 0x422aaa1a8, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
github.com/NebulousLabs/muxado/proto/frame.(*BasicTransport).Read(0x421f18400, 0x422aaa1a8, 0x8, 0x8, 0x13e8392, 0x4220d7a00, 0x421f18470)
	<autogenerated>:139 +0x6b
io.ReadAtLeast(0x19df0a0, 0x421f18400, 0x422aaa1a8, 0x8, 0x8, 0x8, 0x16b2de0, 0x0, 0x19df0a0)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x19df0a0, 0x421f18400, 0x422aaa1a8, 0x8, 0x8, 0x8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/NebulousLabs/muxado/proto/frame.(*BasicTransport).ReadFrame(0x421f18400, 0x19e5760, 0x421f18470, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/frame/transport.go:34 +0x67
github.com/NebulousLabs/muxado/proto.(*Session).reader(0x4236fc000)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:279 +0xa1
created by github.com/NebulousLabs/muxado/proto.NewSession
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:105 +0x488

goroutine 71 [chan receive]:
github.com/NebulousLabs/muxado/proto.(*Session).Accept(0x4236fc000, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:160 +0x5b
github.com/NebulousLabs/muxado.(*sessionAdaptor).Accept(0x422aaa200, 0x100000001708f38, 0x0, 0x60, 0x421e798c0)
	/home/luke/go/src/github.com/NebulousLabs/muxado/adaptor.go:33 +0x37
github.com/NebulousLabs/Sia/modules/gateway.muxadoSession.Accept(0x19e9ca0, 0x422aaa200, 0x1028fef, 0x1708f38, 0x421e2bee8, 0x421e2bf08)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/stream.go:43 +0x35
github.com/NebulousLabs/Sia/modules/gateway.(*muxadoSession).Accept(0x422aaa210, 0x421e2bee0, 0x147277a, 0x1054480, 0x421e2bf20)
	<autogenerated>:24 +0x56
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0x422451b00, 0x1707ec8, 0x421e79860, 0x421c88c60, 0x421e798c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:60 +0x38
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer(0x421c88c60, 0x422451b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:166 +0x11b
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:71 +0x8f

```

**Comment by SerdarN92** [comment]
Hi,

had a exception too. Loaded new Version and it worked. And maybe restart your computer. Hope that helps!

**Comment by tbenz9** [comment]
`SIGBUS` indicates that your disk may have errors. Follow these instructions to check for errors:

- [Windows](http://www.thewindowsclub.com/disk-error-checking-windows-8)
- [Mac](https://support.apple.com/en-us/HT201639)
- [Linux](https://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/) 

The next version of Sia will present this type of error in a more obvious way instead of crashing with a cryptic error message.
