### ISSUE TITLE
Siad doesn't handle out of disk space well

### ISSUE THREAD

**Issue by sokoow** [NebulousLabs/Sia#2237]
```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.057140199 seconds
goroutine 856293 [running]:
runtime/debug.Stack(0x4457c7, 0x0, 0xc420da7c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc420da7e58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420326800, 0xc420da7e58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4249e4a40, 0xc42022e668, 0x0, 0x0, 0x0, 0xf05908, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: write /home/sokoow/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
goroutine 856293 [running]:
runtime/debug.Stack(0x4457c7, 0x0, 0xc420da7aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc420da7c18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420326800, 0xc420da7c18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc42022e668, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4249e4a40, 0xc42022e668, 0x0, 0x0, 0x0, 0xf05908, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: write /home/sokoow/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 856293 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc42022e668, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4249e4a40, 0xc42022e668, 0x0, 0x0, 0x0, 0xf05908, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
```

**Comment by Fornax96** [comment]
You disk is full. You need to free some space.

**Comment by sokoow** [comment]
I know that, yet it should return some nice error message, not crash, right ? :)

**Comment by Fornax96** [comment]
I agree

**Comment by tbenz9** [comment]
I would recommend changing the issue title to something like "Improve error message regarding Disk Space Issues" and see if one of the devs will tag it with the "Programming Task" label.  Otherwise, I would close this issue as the code is performing as expected (but not as desired).

**Comment by tbenz9** [comment]
We are tracking this Feature Request in #2407 

Recommendation to Devs: Close
