### ISSUE TITLE
Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by christoefar** [NebulousLabs/Sia#2346]
Hello, I have received quite a number of these errors:

`
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 19325225 [running]:
runtime/debug.Stack(0x445837, 0x0, 0xc428648b88)
/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc428648c30, 0x1, 0x1)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/types.Currency.Sub(0x0, 0xc420180cf0, 0x2, 0x6, 0xc420fc1400, 0xc42a3dd0e0, 0x2, 0x5, 0x0, 0xc420180cf0, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x15d
github.com/NebulousLabs/Sia/modules/host.renewContractCollateral(0xc42007ef80, 0xd3, 0xd3, 0x0, 0xc423971d10, 0x2, 0x5, 0x0, 0xc423971d40, 0x2, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:44 +0xa6
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc44753f180, 0xde2420, 0xc4214140c0, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:185 +0xb40
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc44753f180, 0xde2420, 0xc4214140c0)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x6c1
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:332 +0xc3
Critical error: negative currency not allowed`

**Comment by eddiewang** [comment]
I have experienced this issue as a host as well.

**Comment by tbenz9** [comment]
Recommendation to Devs: Tag as "bug"

**Comment by mtlynch** [comment]
I'm seeing this in the latest code in `master` (0edf5b998a9ec1aa785e41634ad7bd8350f94262). My stack ends in `routes.go` though:

```
goroutine 4611 [running]:
runtime/debug.Stack(0x447b37, 0x0, 0xc421c48740)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc421c487e8, 0x1, 0x1)
        /home/mike/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc421c48800, 0xc420f72030, 0x2, 0x5, 0x0, 0xc420b72140, 0x2, 0x7, 0x0, 0xc420f72030, ...)
        /home/mike/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x145
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).PeriodSpending(0xc4200764e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mike/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contractor.go:124 +0x880
github.com/NebulousLabs/Sia/modules/renter.(*Renter).PeriodSpending(0xc4203825a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mike/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:423 +0x74
github.com/NebulousLabs/Sia/api.(*API).renterHandlerGET(0xc42020a3f0, 0xe11120, 0xc4212adce0, 0xc420333100, 0x0, 0x0, 0x0)
        /home/mike/go/src/github.com/NebulousLabs/Sia/api/renter.go:156 +0xc0
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.renterHandlerGET)-fm(0xe11120, 0xc4212adce0, 0xc420333100, 0x0, 0x0, 0x0)
        /home/mike/go/src/github.com/NebulousLabs/Sia/api/routes.go:68 +0x66
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4202cd880, 0xe11120, 0xc4212adce0, 0xc420333100)
        /home/mike/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x799
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xe11120, 0xc4212adce0, 0xc420333100)
        /home/mike/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xba
net/http.HandlerFunc.ServeHTTP(0xc4203f2e70, 0xe11120, 0xc4212adce0, 0xc420333100)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc42141ef00, 0xe0c520, 0xc4203f2e70, 0xe11120, 0xc4212adce0, 0xc420333100)
        /home/mike/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x79
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
        /home/mike/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xb7
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

**Comment by lukechampine** [comment]
The bug in that trace seems to be here: https://github.com/NebulousLabs/Sia/blob/0edf5b998a9ec1aa785e41634ad7bd8350f94262/modules/renter/contractor/contractor.go#L124
The spending is larger than the allowance. Perhaps the spending is not being properly reset when the period changes, or perhaps there is a bug that causes the contractor to spend more than the allowance. We should probably handle this by settings `Unspent` to 0 and logging the excess.

**Comment by MeijeSibbel** [comment]
A new log that might be useful: [negative currency not allowed.txt](https://github.com/NebulousLabs/Sia/files/1560939/negative.currency.not.allowed.txt)

**Comment by ChrisSchinnerl** [comment]
@lukechampine I'm pretty sure we fixed that in 1.3.1 by now. If I remember correctly I got that panic on my test node after deleting the renter and contractor json files which caused the allowance to be reset to 0 while `allSpending` for this period was still greater than 0.

**Comment by KaiRo-at** [comment]
I'm seeing stacks like this in 1.3.1 RC2:

goroutine 1603070 [running]:
runtime/debug.Stack(0x4462a7, 0x0, 0xc49ec4b3b0)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc49ec4b458, 0x1, 0x1)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc42085f600, 0xc42008e060, 0x2, 0x5, 0x30bb8f90a8c7a00, 0xc481adc2c0, 0x2, 0x7, 0x0, 0xc42008e060, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x145
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).PeriodSpending(0xc421dbc000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contractor.go:113 +0x604
github.com/NebulousLabs/Sia/modules/renter.(*Renter).PeriodSpending(0xc42164c1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:427 +0x74
github.com/NebulousLabs/Sia/api.(*API).renterHandlerGET(0xc42015c090, 0xe09e60, 0xc422a6f500, 0xc483adfa00, 0x0, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/renter.go:156 +0xc0
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.renterHandlerGET)-fm(0xe09e60, 0xc422a6f500, 0xc483adfa00, 0x0, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:68 +0x66
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc421577940, 0xe09e60, 0xc422a6f500, 0xc483adfa00)
/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x799
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xe09e60, 0xc422a6f500, 0xc483adfa00)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xba
net/http.HandlerFunc.ServeHTTP(0xc4227aa450, 0xe09e60, 0xc422a6f500, 0xc483adfa00)
/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc455d0c060, 0xe05260, 0xc4227aa450, 0xe09e60, 0xc422a6f500, 0xc483adfa00)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x79
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xb7
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues


I probably had my allowance lowered by a Minebox automatism after I had increased it, and I have tried 1.3.1 RC1 and stepped back to 1.3.0, so that can all play into this. Also, the sum of funds in my contracts seems to be far over the allowance set right now.

**Comment by KaiRo-at** [comment]
And this is basically the same line, just that there's a null check there now (not a negative check though):
https://github.com/NebulousLabs/Sia/blob/789adc13d8d7ac7397128ef695e550649fb15ccf/modules/renter/contractor/contractor.go#L113

**Comment by MeijeSibbel** [comment]
output while running RC3:

```
C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\bin>goobox-sync-sia.bat create-allowance
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/meije/Downloads/goobox-sync-sia-0.0.11-win64%20(1)/goobox-sync-sia-0.0.11-win64/lib/log4j-slf4j-impl-2.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/meije/Downloads/goobox-sync-sia-0.0.11-win64%20(1)/goobox-sync-sia-0.0.11-win64/lib/logback-classic-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2017/12/15 08:49:15 INFO  io.goobox.sync.sia.Config - Loading config file C:\Users\meije\AppData\Local\Goobox\goobox.properties
2017/12/15 08:49:15 INFO  io.goobox.sync.sia.Config - Sync directory: C:\Users\meije\Goobox
2017/12/15 08:49:15 INFO  io.goobox.sync.sia.Config - Sync configuration: data pieces = 1, parity pieces = 12
2017/12/15 08:49:17 INFO  io.goobox.sync.sia.command.CreateAllowance - Failed to access sia daemon: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9980
2017/12/15 08:49:17 INFO  io.goobox.sync.sia.command.CreateAllowance - Starting SIA daemon
2017/12/15 08:49:17 INFO  io.goobox.sync.sia.command.CreateAllowance - Waiting SIA daemon starts
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - Execute: C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\sia\siad.exe --api-addr=127.0.0.1:9980 --host-addr=:9982 --rpc-addr=:9981 --sia-directory=C:\Users\meije\AppData\Local\Goobox\sia --modules=cgrtw
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - Sia Daemon v1.3.1
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - Loading...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (0/5) Loading siad...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (1/5) Loading gateway...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (2/5) Loading consensus...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (3/5) Loading transaction pool...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (4/5) Loading wallet...
2017/12/15 08:49:17 DEBUG io.goobox.sync.sia.SiaDaemon - (5/5) Loading renter...
2017/12/15 08:49:22 WARN  io.goobox.sync.sia.command.CreateAllowance - Failed to allocate funds: siad is not ready. please wait for siad to finish loading.
2017/12/15 08:49:24 DEBUG io.goobox.sync.sia.SiaDaemon - Finished loading in 6.438384 seconds
2017/12/15 08:50:22 INFO  io.goobox.sync.sia.command.CreateAllowance - Unlocking the wallet
2017/12/15 08:50:22 INFO  io.goobox.sync.sia.command.CreateAllowance - Allocating 6666666666666666666666692 hastings
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - goroutine 1450 [running]:
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.Stack(0x446dde, 0x0, 0xc0424d33b0)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.PrintStack()
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/build.Critical(0xc0424d3458, 0x1, 0x1)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x9a
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/types.Currency.Sub(0xc04223a200, 0xc042e38cc0, 0x2, 0x5, 0x0, 0xc042dd18c0, 0x2, 0x7, 0xc042c2e900, 0xc042e38cc0, ...)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x14c
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).PeriodSpending(0xc04205ad00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contractor.go:113 +0x60b
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/renter.(*Renter).PeriodSpending(0xc04519e780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:427 +0x7b
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.(*API).renterHandlerGET(0xc04218c360, 0xde8880, 0xc0450f37a0, 0xc046540200, 0x0, 0x0, 0x0)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/renter.go:156 +0xc7
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.renterHandlerGET)-fm(0xde8880, 0xc0450f37a0, 0xc046540200, 0x0, 0x0, 0x0)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:68 +0x6d
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc04358c100, 0xde8880, 0xc0450f37a0, 0xc046540200)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xde8880, 0xc0450f37a0, 0xc046540200)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xc1
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - net/http.HandlerFunc.ServeHTTP(0xc042f8c4e0, 0xde8880, 0xc0450f37a0, 0xc046540200)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/net/http/server.go:1918 +0x4b
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc04654eae0, 0xde3f40, 0xc042f8c4e0, 0xde8880, 0xc0450f37a0, 0xc046540200)
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x80
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xbe
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - Critical error: negative currency not allowed
2017/12/15 08:50:22 DEBUG io.goobox.sync.sia.SiaDaemon - Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
allowance:
  funds: 6.6667 SC
  host: 50
  period: 4320 blocks
  renew-window: 2160 blocks
2017/12/15 08:50:22 INFO  io.goobox.sync.sia.SiaDaemon - Closing SIA daemon
C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\bin>
```

```
C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\bin>goobox-sync-sia.bat wallet
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/meije/Downloads/goobox-sync-sia-0.0.11-win64%20(1)/goobox-sync-sia-0.0.11-win64/lib/log4j-slf4j-impl-2.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/meije/Downloads/goobox-sync-sia-0.0.11-win64%20(1)/goobox-sync-sia-0.0.11-win64/lib/logback-classic-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2017/12/15 08:53:48 INFO  io.goobox.sync.sia.Config - Loading config file C:\Users\meije\AppData\Local\Goobox\goobox.properties
2017/12/15 08:53:48 INFO  io.goobox.sync.sia.Config - Sync directory: C:\Users\meije\Goobox
2017/12/15 08:53:48 INFO  io.goobox.sync.sia.Config - Sync configuration: data pieces = 1, parity pieces = 12
2017/12/15 08:53:50 INFO  io.goobox.sync.sia.command.Wallet - Failed to access sia daemon: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9980
2017/12/15 08:53:50 INFO  io.goobox.sync.sia.command.Wallet - Starting SIA daemon
2017/12/15 08:53:50 INFO  io.goobox.sync.sia.command.Wallet - Waiting SIA daemon starts
2017/12/15 08:53:50 DEBUG io.goobox.sync.sia.SiaDaemon - Execute: C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\sia\siad.exe --api-addr=127.0.0.1:9980 --host-addr=:9982 --rpc-addr=:9981 --sia-directory=C:\Users\meije\AppData\Local\Goobox\sia --modules=cgrtw
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - Sia Daemon v1.3.1
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - Loading...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (0/5) Loading siad...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (1/5) Loading gateway...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (2/5) Loading consensus...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (3/5) Loading transaction pool...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (4/5) Loading wallet...
2017/12/15 08:53:51 DEBUG io.goobox.sync.sia.SiaDaemon - (5/5) Loading renter...
2017/12/15 08:53:55 DEBUG io.goobox.sync.sia.SiaDaemon - Finished loading in 4.4651105 seconds
2017/12/15 08:53:55 INFO  io.goobox.sync.sia.command.Wallet - Unlocking the wallet
wallet address: 48720ff41e276441d3d3ce5c4542c7408bf7877c368c421b7c95f3b8d86a10c9f245b94afbe0
balance: 6.6667 SC
unconfirmed delta: 0.0000 SC
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - goroutine 142 [running]:
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.Stack(0x446dde, 0x0, 0xc0451633b0)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.PrintStack()
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/build.Critical(0xc045163458, 0x1, 0x1)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x9a
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/types.Currency.Sub(0xc045581600, 0xc043d5d5f0, 0x2, 0x5, 0x0, 0xc04361ef80, 0x2, 0x7, 0xc04553b600, 0xc043d5d5f0, ...)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x14c
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).PeriodSpending(0xc04205a4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contractor.go:113 +0x60b
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/renter.(*Renter).PeriodSpending(0xc043e49a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:427 +0x7b
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.(*API).renterHandlerGET(0xc04218e2d0, 0xde8880, 0xc043fa80e0, 0xc0453b0000, 0x0, 0x0, 0x0)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/renter.go:156 +0xc7
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.renterHandlerGET)-fm(0xde8880, 0xc043fa80e0, 0xc0453b0000, 0x0, 0x0, 0x0)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:68 +0x6d
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc04203f580, 0xde8880, 0xc043fa80e0, 0xc0453b0000)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xde8880, 0xc043fa80e0, 0xc0453b0000)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xc1
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - net/http.HandlerFunc.ServeHTTP(0xc04253edb0, 0xde8880, 0xc043fa80e0, 0xc0453b0000)
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /usr/local/go/src/net/http/server.go:1918 +0x4b
current spending:
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc04414a060, 0xde3f40, 0xc04253edb0, 0xde8880, 0xc043fa80e0, 0xc0453b0000)
  download: 0.0014 SC
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x80
  upload: 0.1508 SC
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
  storage: 1.1015 SC
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon -        /home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xbe
  fee: 993.3333 SC
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - Critical error: negative currency not allowed
2017/12/15 08:53:56 DEBUG io.goobox.sync.sia.SiaDaemon - Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
current prices:
  download: 26.2800 SC/TB
  upload: 20.5800 SC/TB
  storage: 173.1000 SC/TB*Month
  fee: 87.2510 SC/contract
2017/12/15 08:53:56 INFO  io.goobox.sync.sia.SiaDaemon - Closing SIA daemon
C:\Users\meije\Downloads\goobox-sync-sia-0.0.11-win64 (1)\goobox-sync-sia-0.0.11-win64\bin>
````

[contractor.log](https://github.com/NebulousLabs/Sia/files/1561957/contractor.log)
[hostdb.log](https://github.com/NebulousLabs/Sia/files/1561958/hostdb.log)
[renter.log](https://github.com/NebulousLabs/Sia/files/1561959/renter.log)

**Comment by DavidVorick** [comment]
*This issue was closed because a fix has been merged into master.

If you see this issue again, it's likely a separate problem, please open a new issue.
