### ISSUE TITLE
Siad fails with the following stacktrace

### ISSUE THREAD

**Issue by rippaio** [NebulousLabs/Sia#2382]
```
goroutine 77 [running]:
runtime/debug.Stack(0x141408b, 0xc4203b1ac0, 0xc4203b1a78)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x87
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x34
github.com/NebulousLabs/Sia/build.Critical(0xc4203b1b68, 0x2, 0x2)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xbb
github.com/NebulousLabs/Sia/persist.SaveJSON.func1(0xc4201e4390, 0x2a, 0x0, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/persist/json.go:149 +0x1f9
github.com/NebulousLabs/Sia/persist.SaveJSON(0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0x0, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/persist/json.go:154 +0xbc
github.com/NebulousLabs/Sia/modules/renter/hostdb.prodDependencies.saveFileSync(0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0xc4203b1e68, 0x1039310)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/dependencies.go:36 +0x95
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*prodDependencies).saveFileSync(0x1ede708, 0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0xc4203f22c0, ...)
	<autogenerated>:9 +0xd5
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).saveSync(0xc4203f2280, 0xc420340960, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:42 +0x222
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedSaveLoop(0xc4203f2280)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:91 +0x14e
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:125 +0x758
Critical error: another thread is saving or loading this file antfarm-data/nick-miner/renter/hostdb.json
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
panic: Critical error: another thread is saving or loading this file antfarm-data/nick-miner/renter/hostdb.json
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues


goroutine 77 [running]:
github.com/NebulousLabs/Sia/build.Critical(0xc4203b1b68, 0x2, 0x2)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/build/critical.go:20 +0x135
github.com/NebulousLabs/Sia/persist.SaveJSON.func1(0xc4201e4390, 0x2a, 0x0, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/persist/json.go:149 +0x1f9
github.com/NebulousLabs/Sia/persist.SaveJSON(0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0x0, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/persist/json.go:154 +0xbc
github.com/NebulousLabs/Sia/modules/renter/hostdb.prodDependencies.saveFileSync(0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0xc4203b1e68, 0x1039310)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/dependencies.go:36 +0x95
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*prodDependencies).saveFileSync(0x1ede708, 0x19db08c, 0x12, 0x19c57d4, 0x3, 0x194f9e0, 0xc4204850c0, 0xc4201e4390, 0x2a, 0xc4203f22c0, ...)
	<autogenerated>:9 +0xd5
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).saveSync(0xc4203f2280, 0xc420340960, 0x0)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:42 +0x222
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedSaveLoop(0xc4203f2280)
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:91 +0x14e
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
	/Users/nick.hansen/PersonalCode/Go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:125 +0x758
```

I'm not able to reproduce and was not interacting with the host or renter modules, so I'm pretty confused as to what's going on.

**Comment by rippaio** [comment]
This is not a bug, this is a programmer error on my end
