### ISSUE TITLE
Certain crashes of siad ruin the Explorer module

### ISSUE THREAD

**Issue by aerrejon** [NebulousLabs/Sia#2432]
From time to time siad crashes with this error report in my Windows Server 2012 R2:

> goroutine 3263627 [running]:
> runtime/debug.Stack(0x44441e, 0x0, 0xc0430a7618)
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x80
> runtime/debug.PrintStack()
>         /usr/local/go/src/runtime/debug/stack.go:16 +0x29
> github.com/NebulousLabs/Sia/build.Critical(0xc0430a76f0, 0x2, 0x2)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xae
> 
> github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(
> 0xc042064a50, 0xe3715b0977bc7484, 0xc7f2bb24ccdf10e7, 0x34d3ce24e6da6000, 0x66e9
> 4fe73a5ad56, 0xc049a0d7a0, 0x1, 0x1, 0xc044902f00, 0x2, ...)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/explorer/update.go
> :282 +0x161
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(
> 0xc042214000, 0xc043479860, 0x1, 0x1, 0xc04524f0c0, 0x2, 0x2)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscrib
> e.go:114 +0x17a
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock
> s(0xc042214000, 0xc045ca5d18, 0x1, 0x1, 0x1e8400, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.g
> o:338 +0x750
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBloc
> k.func1(0xde41c0, 0xc048ad65c0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:529 +0x210
> github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042172000,
> 0xc042861540, 0x11, 0xad6e67, 0x7, 0xc042ad5aa0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66
> +0x339
> github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042172000, 0xc0428
> 61540, 0x11, 0xad6e67, 0x7, 0xc042ad5aa0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76
> +0xd8
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedRPCRelayHe
> ader.func5(0xc043eb5010, 0xc043eb4ff0, 0xc042214000, 0xde41c0, 0xc048ad64a0, 0xc
> 043ac94f0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:459 +0x151
> created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threade
> dRPCRelayHeader
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:463 +0x481
> Critical error: explorer update failed: runtime error: invalid memory address or
>  nil pointer dereference
> Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

The problem is that after restarting siad, any block request to the Explorer module will return several fields with data = 0, including block height, transaction count and others. I am only able to recover the functionality of the module restoring a backup of Sia. I have suffered this issue about 4 times in the last month. 

For SiaStats.info is not a critical issue as I can restore a backup, but I can imagine this could be problematic for other critical apps like wallets or explorers

**Comment by tbenz9** [comment]
The `runtime error: invalid memory address or nil pointer dereference` error also shows up in #2395 and #2374 but in different modules.  Not sure if they're related or not.

Recommendation to Devs: "Bug"
