### ISSUE TITLE
Sia still crashes on initial sync (since months)

### ISSUE THREAD

**Issue by chymian** [NebulousLabs/Sia#2505]
while testing SIA for stability 2 -3 month ago, I ran into SIA always crash on initial sync.
giving it a second try, it still has the same pbl. it's just unable to sync and crashes always around 83  - 88%. I tried 3 times now, always deleting the complete ~/.config/Sia-UI
SIA is running in an LXC with an btrfs-backend.
OS: debian stretch (host)
LXC: Ubuntu 16.10

it's not a out-of disk-space pbl.

```
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1 [running]:
runtime/debug.Stack(0x4457c7, 0x0, 0xc4200a4ec8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4200a5038, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420388160, 0xc4200a5038, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).createWALTmp(0xc4203ae308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:201 +0x1f3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).load(0xc4203ae308, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:259 +0x43
github.com/NebulousLabs/Sia/modules/host/contractmanager.newContractManager(0xde2a20, 0xc4203880e0, 0xc4203b55c0, 0x35, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:163 +0x4ed
github.com/NebulousLabs/Sia/modules/host/contractmanager.New(0xc4203b55c0, 0x35, 0x2, 0xc4203b55c0, 0x35)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:226 +0x5b
github.com/NebulousLabs/Sia/modules/host.newHost(0xde2ba0, 0xf05908, 0xde35c0, 0xc420149b80, 0xde27a0, 0xc4203846e0, 0xde5e80, 0xc4203849a0, 0x7fff0febbbda, 0x5, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:262 +0x4a5
github.com/NebulousLabs/Sia/modules/host.New(0xde35c0, 0xc420149b80, 0xde27a0, 0xc4203846e0, 0xde5e80, 0xc4203849a0, 0x7fff0febbbda, 0x5, 0xc420166540, 0x25, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:298 +0xd8
main.startDaemon(0x0, 0x0, 0x7fff0febbbbf, 0xe, 0x7fff0febbbeb, 0x5, 0x7fff0febbbda, 0x5, 0x0, 0x7fff0febbc2c, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:250 +0xf3c
main.startDaemonCmd(0xc42008efc0, 0xc42005d1d0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc42008efc0, 0xc4200100d0, 0x5, 0x5, 0xc42008efc0, 0xc4200100d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008efc0, 0xaf832c, 0x3b, 0xc420158b40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008efc0, 0xee9020, 0xae0d0e)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Severe error: Unable to create WAL temporary file: open /home/guenter/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: permission denied
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
panic: unable to create WAL temporary file, crashing to avoid corruption

goroutine 1 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).createWALTmp(0xc4203ae308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:202 +0x23a
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).load(0xc4203ae308, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:259 +0x43
github.com/NebulousLabs/Sia/modules/host/contractmanager.newContractManager(0xde2a20, 0xc4203880e0, 0xc4203b55c0, 0x35, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:163 +0x4ed
github.com/NebulousLabs/Sia/modules/host/contractmanager.New(0xc4203b55c0, 0x35, 0x2, 0xc4203b55c0, 0x35)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:226 +0x5b
github.com/NebulousLabs/Sia/modules/host.newHost(0xde2ba0, 0xf05908, 0xde35c0, 0xc420149b80, 0xde27a0, 0xc4203846e0, 0xde5e80, 0xc4203849a0, 0x7fff0febbbda, 0x5, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:262 +0x4a5
github.com/NebulousLabs/Sia/modules/host.New(0xde35c0, 0xc420149b80, 0xde27a0, 0xc4203846e0, 0xde5e80, 0xc4203849a0, 0x7fff0febbbda, 0x5, 0xc420166540, 0x25, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:298 +0xd8
main.startDaemon(0x0, 0x0, 0x7fff0febbbbf, 0xe, 0x7fff0febbbeb, 0x5, 0x7fff0febbbda, 0x5, 0x0, 0x7fff0febbc2c, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:250 +0xf3c
main.startDaemonCmd(0xc42008efc0, 0xc42005d1d0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc42008efc0, 0xc4200100d0, 0x5, 0x5, 0xc42008efc0, 0xc4200100d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008efc0, 0xaf832c, 0x3b, 0xc420158b40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008efc0, 0xee9020, 0xae0d0e)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
```

**Comment by tbenz9** [comment]
This is a well known and understood bug.  It will be fixed in the next release of Sia (1.3.1) that is expected later this month. Searching GitHub for 'unable to create WAL temporary file' returns 18 issues that are likely related.

Recommendation to devs: close
