### ISSUE TITLE
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist

### ISSUE THREAD

**Issue by leonohaodhagain** [NebulousLabs/Sia#2542]
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0x421e461e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x421e46520, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0x421e582c0, 0x421e46520, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0x421d3fb80, 0x427eb56c0, 0x0, 0x0, 0x0, 0x42c78fec0, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:55 +0x1670
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0x427eb56c0, 0x17081f0, 0x427eb56c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0
github.com/NebulousLabs/bolt.(*DB).View(0x421d0c780, 0x421e47248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0x421d3fb80, 0x19deca0, 0x421c711e0, 0xe10076166bd3fb8b, 0x1dffa22c5893d90e, 0xa0af3ab53b521712, 0x301a2f3c14d36997, 0x421d3c800, 0x1052170)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0x421d3fb80, 0x19deca0, 0x421c711e0, 0xe10076166bd3fb8b, 0x1dffa22c5893d90e, 0xa0af3ab53b521712, 0x301a2f3c14d36997, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0x421c711e0, 0x421c711e0, 0x421e84660)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x944
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19ea7c0, 0x421d3fb80, 0x19e9ba0, 0x421c70dc0, 0x421c7b7c0, 0x4d, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276
main.startDaemon(0x0, 0x0, 0x7fff5fbffcfd, 0xe, 0x7fff5fbffd29, 0x5, 0x7fff5fbffd18, 0x5, 0x0, 0x7fff5fbffd87, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x1693
main.startDaemonCmd(0x421c79200, 0x421c7b220, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0x421c79200, 0x421c50070, 0x5, 0x5, 0x421c79200, 0x421c50070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0x421c79200, 0x16fce88, 0x3b, 0x421d4e960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c79200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing consensus...
Closing gateway...
requested item does not exist

**Environment**
* Sia version: 1.2
* OS: OS X Yosemite

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment]
We have seen this error once before in #1629.  It may be solved in the 1.3.0 release and is probably solved in the upcoming 1.3.1 release, I would recommend you update and see if the problem persists.  Alternatively, you can try removing your consensus.db file as a workaround.

Delete the consensus.db file and restart Sia. It is located in:
- **Windows:** Users\<user>\appdata\roaming\Sia-UI\sia\consensus\consensus.db
- **OS X:** $HOME/Library/Application Support/Sia-UI/sia/consensus/consensus.db
- **Linux:** $HOME/.config/Sia-UI/sia/consensus/consensus.db

**Comment by tbenz9** [comment]
Please report back if the bug remains after updating, and/or removing your consensus.db file.

**Comment by leonohaodhagain** [comment]
Currently using "v1.3.0 (Capricorn)"

Strangely - there is no Sia-UI folder in Application Support

**Comment by tbenz9** [comment]
I would recommend asking for help in the #help channel of the Sia Discord.  They will be able to offer real time help finding your consensus.db file and getting you back up and running.

**Comment by tbenz9** [comment]
Closing this due to inactivity.
