### ISSUE TITLE
siad does not exit

### ISSUE THREAD

**Issue by chargr** [NebulousLabs/Sia#2575]
Bug Report
==========
`siad` does not exit after `siac stop`. 

**Environment**
* Sia version: 1.3.1
* OS: Linux
go version go1.9.2 linux/amd64

**Any useful logs**
Built with:
```
go build -a -v -tags 'netgo' -ldflags='-s -w' -o out/siac ./cmd/siac
go build -a -v -tags 'netgo' -ldflags='-s -w' -o out/siad ./cmd/siad
```

Started with:
```
siad -M cghrtw -d /data/sia/siad
```

Version:
```
$ siac version
Sia Client v1.3.1
Sia Daemon v1.3.1
```

Output from siad:
```
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 17.865764719 seconds
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
Caught stop signal, quitting...
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
goroutine 1 [running]:
runtime/debug.Stack(0x446377, 0x0, 0xc4204d1988)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4204d1af8, 0x1, 0x1)
        /home/chris/go/sia/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0xaad26b, 0xe, 0xa9d6f2, 0x5, 0xa9d6f7, 0x5, 0x0, 0x7fff8dcad99e, ...)
        /home/chris/go/sia/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:185 +0x4b1
main.startDaemonCmd(0xc4200b0d80, 0xc4200507c0, 0x0, 0x4)
        /home/chris/go/sia/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200b0d80, 0xc42000e150, 0x4, 0x4, 0xc4200b0d80, 0xc42000e150)
        /home/chris/go/sia/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200b0d80, 0xac9370, 0x3b, 0xc42007f900)
        /home/chris/go/sia/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200b0d80, 0xee4f80, 0xab207c)
        /home/chris/go/sia/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
        /home/chris/go/sia/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: close tcp 127.0.0.1:9980: use of closed network connection
ThreadGroup already stopped
ThreadGroup already stopped
ThreadGroup already stopped
ThreadGroup already stopped
ThreadGroup already stopped
ThreadGroup already stopped
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.
```

**Comment by chargr** [comment]
after the `siac stop` command, siad is still hitting io pretty hard (it is writing like this while running too).  i am not sure what it's writing.  it's generating about 200 write ops/sec.

```
Total DISK READ :     817.24 K/s | Total DISK WRITE :      46.96 M/s
Actual DISK READ:     817.24 K/s | Actual DISK WRITE:      81.31 M/s
  PID  PRIO  USER     DISK READ DISK WRITE>  SWAPIN      IO    COMMAND                                  
 1420 be/4 sia         0.00 B/s   46.68 M/s  0.00 %  0.00 % siad -M cghrtw -d /data/sia/siad
```

**Comment by tbenz9** [comment]
I was able to reproduce this on Linux as well.

**Comment by teepoe** [comment]
I am having the same problem with my SIA-UI, it's not working and I can't get to my coins. did you figure it out??
t

**Comment by tbenz9** [comment]
@teepoe this issue does not affect access to your coins.  If you're having trouble with Sia-UI I would recommend asking for help in the #Help channel of the Sia Discord.

**Comment by tbenz9** [comment]
@lukechampine this issue may be preventing users from running siad as a service (for example `systemctl stop siad.service` won't work properly if `siad` never exits).

**Comment by chargr** [comment]
with 1.3.0 and previous versions I had the same 'never' stopping issue, but I could work around it.  In previous versions the gateway would hang shutting down, because of open connections (i waited upwards of 30 minutes before taking drastic action).  if I killed them the daemon would shutdown cleanly, so in my init script I just had a tcpkill for port 9981.  Now the connections do die on their own in a reasonable amount of time but the last thing in console is still `Closing gateway...`

I have both ipv6 and ipv4 configured and capable of both incoming/outgoing connections.

I'll throw out some more OS specifics: `Linux desktop 4.14.11-1-ARCH #1 SMP PREEMPT Wed Jan 3 07:02:42 UTC 2018 x86_64 GNU/Linux`

**Comment by lukechampine** [comment]
Seems like the gateway is not closing connections quickly enough during shutdown. Unfortunately this will probably be tricky to debug. It's not clear whether the issue is in our code, or in the stream multiplexing package that we use (smux). I would appreciate some community help in tracking down this one.

**Comment by tbenz9** [comment]
I've attached a screenshot: the left shows my `siad` process hung.  The right shows my open TCP connections.  I'd be happy to provide SSH keys to this Linux VM if you can't reproduce it in your own environment. 

![screenshot 2018-01-26 at 9 02 41 pm](https://user-images.githubusercontent.com/1961202/35468852-4b72ef7a-02dc-11e8-9fe9-ebbe5e294fd3.png)

What else can the community do to help diagnose and test this bug?

**Comment by tbenz9** [comment]
I let my `siac stop` run over night and It never closed, but I don't have any open TCP connections left.

![screenshot 2018-01-27 at 10 36 41 am](https://user-images.githubusercontent.com/1961202/35479179-dd7c5608-03a5-11e8-8aaa-2a4da35df96f.png)

**Comment by lukechampine** [comment]
The most helpful thing to do is to generate a stack trace, which you can do by pressing `Ctrl+\` on Linux. If you do this after it's been hung for a while, it should be easy for us to identify which threads are stuck. There may be a lot of output, so if you do this, it's probably easiest to run `siad 2>&1 | tee siad.log` to capture the output to a file.

**Comment by tbenz9** [comment]
That did not generate a stack trace:

```
root@sia1:~# siad 2>&1 | tee siad.log
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.389631086 seconds
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
^\Quit
root@sia1:~#
root@sia1:~# tail siad.log
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.389631086 seconds
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
root@sia1:~#
```

**Comment by lukechampine** [comment]
dang, I think it's because `tee` is receiving the signal, not `siad`. You can either run it without `tee`, or run `kill -SIGQUIT $pidof(siad)` to send the signal directly to `siad`.

**Comment by chargr** [comment]
[issue_2575.log](https://github.com/NebulousLabs/Sia/files/1680483/issue_2575.log)

**Comment by lukechampine** [comment]
Thanks @chargr, I think I've identified the issue. Basically, siad will shutdown properly if you kill it with Ctrl-C, but if you shut it down via the API, it will hang. I should be able to get a fix out soon.

**Comment by chargr** [comment]
@lukechampine thank you luke, yet again.
