### ISSUE TITLE
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...

### ISSUE THREAD

**Issue by kashkid88** [NebulousLabs/Sia#2581]
**My wallet was syncing to the network, it got to 40% and then crashed. It said siad has exited unexpectedly, and then sent this message:**

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.2670152 seconds

Wallet: scanned to height 800...
Wallet: scanned to height 1400...
Wallet: scanned to height 1900...
Wallet: scanned to height 2300...
Wallet: scanned to height 2800...
Wallet: scanned to height 3300...
Wallet: scanned to height 9000...
Wallet: scanned to height 9500...
Done!
goroutine 309206 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0423efdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0423eff20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421f2040, 0xc0423eff20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04e4ecdf0, 0xc04206de08)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Kashbot\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Kashbot\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: invalid page type: 0: 14

goroutine 30 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0x3ad1)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0xc04899c7e0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0x54b8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0xc047fcd8f0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0x56d9)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0xc047fcd730)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0x70dd)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc04a943270, 0xc047a9b5a0, 0x20, 0x20, 0x0, 0x0, 0x0, 0xc042020c00, 0x340000, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc048814f80, 0xc047a9b5a0, 0x20, 0x20, 0xf06bb0, 0x0, 0x0, 0xc0424b8900, 0xde2420)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x14d
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).putTransaction(0xc042065340, 0xc043213260, 0x18bb48d32c72b588, 0x60f141ae4f1fd133, 0x24fdb309bf003b24, 0xe2ac455255db0b3f, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/database.go:123 +0xf3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc042065340, 0x316c2a1bc83313e8, 0xcad0213613676db6, 0xda397d9a49e85979, 0xddb63e6fb2d34a4a, 0x0, 0x0, 0x0, 0xc0424a38c0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:200 +0x49e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc042125b80, 0x0, 0x0, 0x0, 0xc04236e1e0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:114 +0x17a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042125b80, 0xc044b5e800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:338 +0x750
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042125b80, 0xde41c0, 0xc047c1e520, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc047c1e520, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042064dc0, 0xc04375ea00, 0x12, 0xaddb78, 0xa, 0xc04416a720, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042064dc0, 0xc04375ea00, 0x12, 0xaddb78, 0xa, 0xc04416a720, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042125b80, 0xc04a945ef0, 0xc04a945eb0, 0xc04a945eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042125b80, 0xc042171c40, 0x87931a)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421c0c30, 0xc042125b80, 0xde4440, 0xc042064dc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641

Now everytime I log in  it says it is upgrading to a new version and sends through the following message, it completely crashes and I don't access to any features of the wallet: 

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: invalid page type: 227055576406818817: 9b48

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042075308, 0xc0421f3ba0, 0x20, 0x20, 0x3a93)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc042075308, 0xc0421f3ba0, 0x20, 0x20, 0xc0420f41c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042075308, 0xc0421f3ba0, 0x20, 0x20, 0x4187)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc042075308, 0xc0421f3ba0, 0x20, 0x20, 0xc042050070)

**Environment**
* Sia version: 1.6.4
* OS: Windows 7 

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment]
@lukechampine This looks like a new error to me.  I can't quite distinguish if its Bolt related or WAL related.
