### ISSUE TITLE
Sia has exited unexpectedly

### ISSUE THREAD

**Issue by bfeuer** [NebulousLabs/Sia#2674]
Error Log:
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.345512404 seconds

Wallet: scanned to height 137968...
Wallet: scanned to height 138132...
Wallet: scanned to height 138241...
Done!
panic: page 1409843 already freed

goroutine 31 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc42006dd10, 0x38be, 0x161fdf000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x301
github.com/NebulousLabs/bolt.(*node).spill(0xc4236f7e30, 0xc421b0e360, 0x19ef040)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x210
github.com/NebulousLabs/bolt.(*node).spill(0xc4236f7dc0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*node).spill(0xc422776850, 0xc421ae1100, 0x19ef040)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*node).spill(0xc4227767e0, 0xc4215c8030, 0xc42106cc50)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc42226c240, 0xc42106cd00, 0xd)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4d3
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc4209a2018, 0x7a9b3f1e5, 0x1b00c40)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x417
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc4209a2000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x129
github.com/NebulousLabs/bolt.(*DB).Update(0xc420134780, 0xc42106d2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf2
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc4200dbb80, 0xc42165fc00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f2
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4200dbb80, 0x19f2740, 0xc4203a7280, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0x19f2740, 0xc4203a7280, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200d26e0, 0xc420273200, 0x11, 0x16ba9b7, 0xa, 0xc420178b90, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200d26e0, 0xc420273200, 0x11, 0x16ba9b7, 0xa, 0xc420178b90, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc4200dbb80, 0xc42106def0, 0xc42106de98, 0xc42106dea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x127
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc4200dbb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178570, 0xc4200dbb80, 0x19f2f40, 0xc4200d26e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3e4
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x64f

**Comment by tbenz9** [comment]
Duplicate of #2413 

Steps to fix: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
