### ISSUE TITLE
Critical error: negative currency not allowed on host with 1.3.1

### ISSUE THREAD

**Issue by kaN5300** [NebulousLabs/Sia#2733]
# BUG REPORT

**Stack Trace or error message**
goroutine 103800 [running]:
runtime/debug.Stack(0x446e57, 0x0, 0xc424c6a040)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc424c6a0e8, 0x1, 0x1)
        /root/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc42110a000, 0xc4245be510, 0x2, 0x6, 0x0, 0xc4245be6f0, 0x2, 0x6, 0xc42394c000, 0xc4245be510, ...)
        /root/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x145
github.com/NebulousLabs/Sia/modules/host.renewContractCollateral(0xc42110a000, 0x1e, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42394c0f0, 0x2, ...)
        /root/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:44 +0x1bd
github.com/NebulousLabs/Sia/modules/host.(*Host).managedVerifyRenewedContract(0xc4200c6580, 0xc42110a000, 0x1e, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42394c0f0, ...)
        /root/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:266 +0x655
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc4200c6580, 0xde5480, 0xc42486a010, 0x0, 0x0)
        /root/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:126 +0x42d
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc4200c6580, 0xde5480, 0xc42486a010)
        /root/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x804
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
        /root/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:322 +0xc3
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

General Info:
        Connectability Status: Host appears to be working.

Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          40 Weeks
        maxdownloadbatchsize: 256.00 MB
        maxrevisebatchsize:   256.00 MB
        netaddress:           siad.molokanov.me:9982 (manually specified)
        windowsize:           24 Hours

        collateral:       500 SC / TB / Month
        collateralbudget: 230 KS
        maxcollateral:    10 KS Per Contract

        mincontractprice:          0 H
        mindownloadbandwidthprice: 5 SC / TB
        minstorageprice:           170 SC / TB / Month
        minuploadbandwidthprice:   5 SC / TB

Host Financials:
        Contract Count:               1263
        Transaction Fee Compensation: 210.4 SC
        Potential Fee Compensation:   375.2 SC
        Transaction Fee Expenses:     0 H

        Storage Revenue:           45.05 SC
        Potential Storage Revenue: 74.03 SC

        Locked Collateral: 230.2 KS
        Risked Collateral: 4.195 KS
        Lost Collateral:   0 H

        Download Revenue:           440.1 uS
        Potential Download Revenue: 1.145 mS
        Upload Revenue:             47.32 mS
        Potential Upload Revenue:   18.97 mS

RPC Stats:
        Error Calls:        36
        Unrecognized Calls: 20
        Download Calls:     6
        Renew Calls:        17
        Revise Calls:       17
        Settings Calls:     1360
        FormContract Calls: 13

Storage Folders:
    Used         Capacity     % Used    Path
    1.2043 TB    5.0997 TB    23.62     /root/go/bin/storage

root@siad:~/go/bin/host # tail host.log
2018/02/05 11:49:20.269058 errors.go:151: internal error: error with 130.237.96.136:33488: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract
2018/02/05 11:50:29.448373 errors.go:151: internal error: error with 130.237.96.136:34048: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract
2018/02/05 11:52:32.114944 errors.go:151: communication error: error with 92.214.190.81:55758: incoming RPCReviseContract failed: revision iteration failed: rejected proposed modifications: unable to verify updated contract: expected at least 1466676261894630670336 to be exchanged, but 1289848968525078311277 was exchanged: rejected for high paying renter valid output
2018/02/05 11:57:25.681659 errors.go:151: internal error: error with 104.168.152.120:41810: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract
2018/02/05 12:02:56.385840 errors.go:151: internal error: error with 130.237.96.136:39824: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract
2018/02/05 12:07:10.541336 errors.go:151: communication error: error with 92.214.190.81:33996: incoming RPCReviseContract failed: revision iteration failed: rejected proposed modifications: unable to verify updated contract: expected at least 1466346154635378556928 to be exchanged, but 1289554784702857971829 was exchanged: rejected for high paying renter valid output
2018/02/05 12:11:58.739583 errors.go:151: internal error: error with 130.237.96.136:44030: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract
2018/02/05 12:19:15.928095 errors.go:151: communication error: error with 92.214.190.81:41256: incoming RPCReviseContract failed: revision iteration failed: rejected proposed modifications: unable to verify updated contract: expected at least 1466181101005752500224 to be exchanged, but 1289407692791747802104 was exchanged: rejected for high paying renter valid output
2018/02/05 12:41:02.419755 errors.go:151: communication error: error with 92.214.190.81:54370: incoming RPCReviseContract failed: revision iteration failed: rejected proposed modifications: unable to verify updated contract: expected at least 1466181101005752500224 to be exchanged, but 1289407692791747802104 was exchanged: rejected for high paying renter valid output
2018/02/05 12:41:22.661471 errors.go:151: internal error: error with 130.237.96.136:57712: incoming RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
May be this is happening when the hoster is out of collateral budget.

**Environment**
* Sia version: v1.3.1
* OS: FreeBSD 11.1-STABLE #3 r327736

**Comment by kaN5300** [comment]
Redownloaded transaction pool. Still getting the same errors.

**Comment by tbenz9** [comment]
Related to #1321 
I see a couple of things going on here:  The `Critical error: negative currency not allowed` is most concerning because that was supposedly fixed in 1.3.1.  Are you still seeing this issue and is it still crashing Sia?

The `RPCRenewContract failed: verification of renewal failed: host has reached its collateral budget and cannot accept the file contract` is just informational, the host ran out of collateral so you will form a new contract with a different host instead.  This is not a bug.

edit: I edited your issue to add some clearer formatting.
