### ISSUE TITLE
#panic: bolt.DB.meta(): invalid meta pages

### ISSUE THREAD

**Issue by wayne2oo8** [NebulousLabs/Sia#2775]
Wallet stopped syncing and I get this error when restarting program, does not synchronize farther than 21%

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.227013 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 2792 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc0420712c0, 0xc0441664c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xc9
github.com/NebulousLabs/bolt.(*meta).copy(...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:50
github.com/NebulousLabs/bolt.(*Tx).init(0xc0440e4000, 0xc0420712c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:50 +0xb3
github.com/NebulousLabs/bolt.(*DB).beginTx(0xc0420712c0, 0xc0420d5d44, 0x4426e9, 0x15696ffc60)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:491 +0xab
github.com/NebulousLabs/bolt.(*DB).Begin(0xc0420712c0, 0xc000000000, 0xc04226c8c0, 0x473414, 0x828757)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:468 +0x75
github.com/NebulousLabs/bolt.(*DB).View(0xc0420712c0, 0xc0427afc38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:618 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc0420d5b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:259 +0x114
github.com/NebulousLabs/Sia/api.(*API).consensusHandler(0xc04218a750, 0xdea8c0, 0xc0421be000, 0xc042150900, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/consensus.go:24 +0x52
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.consensusHandler)-fm(0xdea8c0, 0xc0421be000, 0xc042150900, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc042310140, 0xdea8c0, 0xc0421be000, 0xc042150900)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xdea8c0, 0xc0421be000, 0xc042150900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc0423204e0, 0xdea8c0, 0xc0421be000, 0xc042150900)
	/usr/local/go/src/net/http/server.go:1918 +0x4b
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc0427c8060, 0xde5f80, 0xc0423204e0, 0xdea8c0, 0xc0421be000, 0xc042150900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x80
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xbe

**Comment by wayne2oo8** [comment]
C: Drive was full, I think this issue is resolved.  I'll update when it has fully synced
