### ISSUE TITLE
Bootstrapping consensus from siahub produces error.

### ISSUE THREAD

**Issue by xurious** [NebulousLabs/Sia#2790]
# BUG REPORT

Attempting to bootstrap consensus from siahub results in an error. 

**Stack Trace or error message**
```
user@server:~/Projects/bin$ ./siad -M gct
Sia Daemon v1.3.2
Loading...
(0/3) Loading siad...
(1/3) Loading gateway...
(2/3) Loading consensus...
(3/3) Loading transaction pool...
panic: page 9838 already freed

goroutine 35 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*freelist).free(0xc4201864b0, 0x2ee9e, 0x7f15ea66e000)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/freelist.go:143 +0x4ad
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).free.func1(0x7f15ea66e000, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:682 +0x51
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket)._forEachPageNode(0xc42cb60b40, 0x266e, 0x0, 0xc42c4fc288)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:504 +0x87
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).forEachPageNode(0xc42cb60b40, 0xc42c4fc288)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:497 +0x7c
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).free(0xc42cb60b40)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:680 +0x5f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).DeleteBucket(0xc42c102a98, 0xc42ca5ef60, 0xd, 0x10, 0x10, 0xc42cb60b40)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:248 +0x2ab
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).DeleteBucket(0xc42c102a80, 0xc42ca5ef60, 0xd, 0x10, 0xc42cb60b40, 0xc42ca5ef60)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:121 +0x4f
github.com/NebulousLabs/Sia/modules/consensus.deleteDSCOBucket(0xc42c102a80, 0x22e33)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:550 +0x11f
github.com/NebulousLabs/Sia/modules/consensus.applyMaturedSiacoinOutputs(0xc42c102a80, 0xc42c28c580)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:101 +0x6d0
github.com/NebulousLabs/Sia/modules/consensus.applyMaintenance(0xc42c102a80, 0xc42c28c580)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:191 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc42c102a80, 0xc42c28c580, 0xc420041a40, 0x2)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:231 +0x1e8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc420176780, 0xc42c102a80, 0xc42c28c580, 0x0, 0x0, 0x0, 0xd00000000000000, 0x7710efaddd779742)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x221
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc420176780, 0xc42c102a80, 0xc42c28c580, 0x100000000000000, 0xbff8b06e2f0eb9c, 0x464162ec3bfe8ec6, 0xdf930666288120dc, 0x865bc8bd, 0x5a8f2e88, 0xc42b4c0b80, ...)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xac
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc420176780, 0xc42c102a80, 0x100000000000000, 0xbff8b06e2f0eb9c, 0x464162ec3bfe8ec6, 0xdf930666288120dc, 0x865bc8bd, 0x5a8f2e88, 0xc42b4c0b80, 0x1, ...)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:165 +0x106
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc42c102a80, 0xae87e0, 0xc42c102a80)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x3c6
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc420132780, 0xc42c4fd2f8, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:673 +0x9a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420176780, 0xc4201cb000, 0xa, 0xa, 0x0, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:244 +0x41d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420176780, 0xdf2660, 0xc4201d4960, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf2660, 0xc4201d4960, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc42006f080,0xc42007ac60, 0x12, 0xab868a, 0xa, 0xc420174850, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc42006f080, 0xc42007ac60, 0x12, 0xab868a, 0xa, 0xc420174850, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420176780, 0xc42c4fdef0, 0xc42c4fde98, 0xc42c4fdea0, 0x0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x127
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420176780, 0xc420028fc0, 0x0)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc4201745f0, 0xc420176780, 0xdf2e60, 0xc42006f080)
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3e4
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /home/user/Projects/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x64f
user@server:~/Projects/bin$
```

**Expected Behavior**

Scans consensus and resumes from max height of bootstrapped consensus.

**How to reproduce it (as minimally and precisely as possible)**

Go get sia, wget siahub conensus file, ungzip, start siad, errors out.

**Environment**
* Sia version: 1.3.2
* OS: Debian 9 x64

**Comment by xurious** [comment]
Ran the bolt DB check: 

page 2316628: unreachable unfreed
page 2316629: unreachable unfreed
10547 errors found
invalid value

I'll DL the consensus from scratch, I'm wondering if Sanasol's is corrupted in some manner.

**Comment by tbenz9** [comment]
@S-anasol You might want to build consensus.db from scratch with 1.3.2 since it includes the new coreos/bbolt package which is supposed to help with these errors.

I'm going to close this issue since it's probably more appropriate on https://github.com/S-anasol/siahub and the page already freed is being tracked in #2413.

**Comment by xurious** [comment]
Certainly doesn't need to build a copy from scratch. Just pulled a copy from my stable 1.3.1 install.  1.3.2 loaded it up correctly. 

@S-anasol Want a ticket made for this?

**Comment by tbenz9** [comment]
Did  you run the bolt check against the stable 1.3.1 copy?  Just curious what the results are.

**Comment by xurious** [comment]
Posted this in #contributors. (As it was my testing box, forgot to start siad since when I rand the bolt DB check last week.)

1.3.1, installed few months ago. -M gcte. ubuntu 16.04.
Consensus: 
page 2248728: unreachable unfreed
page 2248729: unreachable unfreed
1609 errors found
invalid value

tPool:
page 194796: unreachable unfreed
3 errors found
invalid value
