### ISSUE TITLE
"Files" tab always shows "Loading Files"

### ISSUE THREAD

**Issue by eNIghERnInTRATO** [NebulousLabs/Sia#2802]
Sia UI loads up normally, but then the "files" tab shows "loading files" but never changes. Eventually, after several hours, Sia client takes all RAM and runs the HD up to 100% making the computer impossible to use. 

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1875.6034773 seconds

Wallet: scanned to height 143513...
Wallet: scanned to height 143513...
Wallet: scanned to height 143513...
Wallet: scanned to height 143534...
Wallet: scanned to height 143579...
Done!
goroutine 357176 [running]:
runtime/debug.Stack(0x446d5e, 0xc076e6feb8, 0xc076e6fe80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc076e6ff18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0535f94a0, 0xc0c0198640, 0xc04ecb5600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:159 +0x18d
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:154 +0x1e3
Severe error: api call is taking more than 60 minutes to return: /renter/files
goroutine 357177 [running]:
runtime/debug.Stack(0x446d5e, 0xc04556feb8, 0xc04556fe80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04556ff18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04cd74e40, 0xc0c0198680, 0xc0793fe400)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:159 +0x18d
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:154 +0x1e3
Severe error: api call is taking more than 60 minutes to return: /renter/files
(continues repeating last 12 lines indefinitely

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
This has been the behavior since 2/24
Desktop
* Sia version:1.3.1
* OS:Win 10 Pro

**Comment by tbenz9** [comment]
We have seen this error pop up before but haven't been able to reproduce it.  Can you think of anything that might have caused this error?  Maybe unsupported characters in your files, a computer crash before the error first appeared, etc.

Are you using Sia to store files on the network?  How many, and what state are they in?

**Comment by eNIghERnInTRATO** [comment]
Not really, I started running the client on my window 10 computer in order to upload/backup our image library. It was running 'okay' taking up all my upload bandwidth while it synced the all the folders and files.... I say 'okay' because I didn't realize that it would be taking up as much disk I/O percentage as it had to... the Photos folder I was backing up was on my system drive. Nonetheless, despite shutting down and restarting periodically, it going fine until the 24th.... I know it was that date because that was the day the small uploading charges stopped.

I suppose there could be usupported characters, but everything should have been titled in english.  

Other than the problem with files, I can use the terminal commands and post the results.... are there any that would give you more info?

**Comment by eNIghERnInTRATO** [comment]
Alright... well... I'm getting pretty sick of Sia UI.  Time to write up my experiences for a blog post... here will be the highlights:

A) The issue above... I did everything correctly, was uploading my files, many of which were up to 3x redundancy. I was abiding the way sia was TOTALLY taking up all of my upload bandwidth because I thought, hey... once it is all up loaded to the network, it will stop doing that. Days turned into a week... and then the above issue happened.

B) I like the whole idea, and totally understand that others may be having no issues whatsoever. I like the potential of hosting, but so far, other than 12 potential sia from hosting rewards, all the problems I'm starting to have with my otherwise stable win10 computer are not worth the fractions of pennies in potential "profit." 

C) I like the idea of renting space on the decentralized 'cloud', seems to solve a LOT of problems with centralized cloud storage, but concepts and ideals aside, the 600 Sia seemingly "lost" to rental contracts for files that (luckily I haven't lost) are where? and accessible from the network, how? See A

D) Total resource drain. I understand that the sia blockchain has to be stored on the machine in order to synchronize, but I didn't realize that by trying to upload my files from the same drive as the %appdata%, the drive's resources would be SO reduced as to make everything else bog down to usability. Actually, I'm only guessing that this is the issue.... since experiencing the problem that started this issue ticket, siad STILL bogs down the system drive while it is "loading files" forever.

E) RAM drain..... WTH is up with the memory leak? I takes about 8 to 12 hours before sia is taking up substantial amounts of the 16gb of RAM I have available. 

So, how do I get out of this thing? I have hosting and rental contracts, but I notice that sia.tech and the medium blogs don't have a lot on how to cancel contracts and get one's computer back. Can I get help with that?

**Comment by tbenz9** [comment]
There is no way to cancel contracts, they are, by definition, binding.  If you simply shut down Sia while you still have hosting contracts you will lost the collateral for those contracts.  There is no refund process for contracts.  I suggest you do some additional research into how Sia works before investing time, money, and effort into making it work for your use case.

Thanks for your feedback, It certainly sounds like you're having an atypical experience.  Sia does not perform optimally for files less than 40MiB.  If you have 53GB of files that are less than 40MiB Sia is going to struggle.  I don't have an answer for many of your questions/concerns raised in this issue so I'll defer to a Sia team member for those.

**Comment by chrsch** [comment]
I just want to second the "Loading Files" issue. This started at about 4000 files in renter module for me. In SIA-UI they are no longer visible (probably timeout) but ./siac renter still lists the files after about 10-11 seconds delay on cmdli.

**Comment by chrsch** [comment]
Just wanted to add info this is as simple as a timeout happening in the Sia-UI while waiting for response from Sia API. So basically this is an issue with scaling and Sia API performance.
