### ISSUE TITLE
1.32 Crashing since update on macOS.. disappointing

### ISSUE THREAD

**Issue by MichelSakr** [NebulousLabs/Sia#2987]
Like really guys? .. if a stable UI cannot be released, how can we talk about the whole Sia project? .. really becoming disappointed by the project..
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.781235923 seconds
panic: page 795069 already freed

goroutine 67 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*freelist).free(0xc420069d70, 0x4375c, 0xccd69000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/freelist.go:143 +0x4ad
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).free.func1(0xccd69000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:682 +0x51
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket)._forEachPageNode(0xc42562f180, 0xc21bd, 0x0, 0xc424fa8288)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:504 +0x87
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).forEachPageNode(0xc42562f180, 0xc424fa8288)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:497 +0x7c
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).free(0xc42562f180)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:680 +0x5f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).DeleteBucket(0xc4243b16d8, 0xc420c49f60, 0xd, 0x10, 0x10, 0xc42562f180)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:248 +0x2ab
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).DeleteBucket(0xc4243b16c0, 0xc420c49f60, 0xd, 0x10, 0xc42562f180, 0xc420c49f60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:121 +0x4f
github.com/NebulousLabs/Sia/modules/consensus.deleteDSCOBucket(0xc4243b16c0, 0x2550a)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:550 +0x11f
github.com/NebulousLabs/Sia/modules/consensus.applyMaturedSiacoinOutputs(0xc4243b16c0, 0xc4257609a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:101 +0x6d0
github.com/NebulousLabs/Sia/modules/consensus.applyMaintenance(0xc4243b16c0, 0xc4257609a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:191 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc4243b16c0, 0xc4257609a0, 0xc425bfc060, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:231 +0x1e8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc4200bdb80, 0xc4243b16c0, 0xc4257609a0, 0x0, 0x0, 0x0, 0x400000000000000, 0x864e011d93d0a10d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x221
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc4200bdb80, 0xc4243b16c0, 0xc4257609a0, 0x0, 0x9753874825273784, 0x4c58c4186be4e2ea, 0x3f906023e99b5da2, 0x95883084, 0x5aea25e1, 0xc42577e400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xac
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc4200bdb80, 0xc4243b16c0, 0x0, 0x9753874825273784, 0x4c58c4186be4e2ea, 0x3f906023e99b5da2, 0x95883084, 0x5aea25e1, 0xc42577e400, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:165 +0x106
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc4243b16c0, 0x16f0920, 0xc4243b16c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x3c6
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc420116780, 0xc424fa92f8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:673 +0x9a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc4200bdb80, 0xc425c14000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:244 +0x41d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4200bdb80, 0x19fb800, 0xc421ca7a20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0x19fb800, 0xc421ca7a20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200b46e0, 0xc42026f9c0, 0x12, 0x16c0900, 0xa, 0xc425cfc340, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200b46e0, 0xc42026f9c0, 0x12, 0x16c0900, 0xa, 0xc425cfc340, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc4200bdb80, 0xc424fa9ef0, 0xc424fa9e98, 0xc424fa9ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x127
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc4200bdb80, 0xc4200297c0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc42015e5d0, 0xc4200bdb80, 0x19fbf00, 0xc4200b46e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3e4
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x64f
**Expected Behavior**
Sia-UI should not crash
**How to reproduce it (as minimally and precisely as possible)**
While launching Sia-UI it crashes with error
**Environment**
* Sia version: 1.32
* OS: MAC OSX 10.13.3 High sierra

**Comment by MichelSakr** [comment]
Well negative feedback is also constructive, otherwise the project will be living in a dream scenario.. when things go south someone has to point it out.. The user experience is at its lowest, and if the developers fail to see that it is utopic.. find a solution, charge for the client or fix all these bugs or phase out the Mac version if they cannot cope! the last 3 releases failed to run properly on a Mac
