### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SkyCrypto** [NebulousLabs/Sia#3120]
tried
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 4.832674 seconds
panic: assertion failed: read: zero-length inode key

goroutine 9 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt._assert(0xa53c00, 0xaccd87, 0x1b, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:1139 +0xfd
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*node).read(0xc05c69e070, 0x8072e000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/node.go:178 +0xd4
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).node(0xc0562c3000, 0x73e, 0xc05c69e000, 0xc05c69e000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:664 +0x134
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*node).childAt(0xc05c69e000, 0x26, 0x14)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/node.go:77 +0x66
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).node(0xc05db5ea90, 0xc05bfc1300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:373 +0x12f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).Put(0xc0562c3000, 0xc05bfc1300, 0x20, 0x20, 0xc04951a280, 0x50, 0xa0, 0x9c90b62a9b2f924, 0x55b8ca8d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:302 +0x208
github.com/NebulousLabs/Sia/modules/consensus.appendChangeLog(0xc046f6c2a0, 0x0, 0x0, 0x0, 0xc05bfc12e0, 0x1, 0x1, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/changelog.go:61 +0x1fa
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc04213b400, 0xc046f6c2a0, 0x200000000000000, 0xb38d11c2aa585973, 0x5cb2dbce4792a327, 0x9c90b62a9b2f924, 0x55b8ca8d, 0x5a7d25ab, 0xc05e111f80, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:174 +0x3c6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc046f6c2a0, 0xaf0d78, 0xc046f6c2a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:261 +0x3a8
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc042130780, 0xc05869d330, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:673 +0x97
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc04213b400, 0xc04221cc00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:243 +0x41a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc04213b400, 0xb62660, 0xc04e6d0840, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4dc
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb62660, 0xc04e6d0840, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420d4b00, 0xc0421e0dc0, 0x12, 0xabd392, 0xa, 0xc042024c30, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2b2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420d4b00, 0xc0421e0dc0, 0x12, 0xabd392, 0xa, 0xc042024c30, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xcb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc04213b400, 0xc05db5ff18, 0xc05db5fec0, 0xc05db5fec8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x11f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc04213b400, 0xc0420fb5e0, 0xc0420fb600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.NewCustomConsensusSet.func1(0x1, 0xc04213b400, 0xc042164590, 0xb634a0, 0xc0420d4b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:160 +0x37a
created by github.com/NebulousLabs/Sia/modules/consensus.NewCustomConsensusSet
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:153 +0x626

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by zurh1** [comment]
Hello ! did you complete this problem?
