### ISSUE TITLE
Bag report

### ISSUE THREAD

**Issue by zurh1** [NebulousLabs/Sia#3166]
# BUG REPORT
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 5.868523511 seconds
**Stack Trace or error message**
socket hang up
**Expected Behavior**
want to login to my wallet, loaded siad, and have a this bug
**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:1.3.3
* OS: mac os High Sierra 10.13.3

**Comment by zurh1** [comment]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
unexpected fault address 0x254564008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x254564008 pc=0x11d42e7]

goroutine 1 [running]:
runtime.throw(0x16ae943, 0x5)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc42014ad80 sp=0xc42014ad60 pc=0x1029c41
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc42014add0 sp=0xc42014ad80 pc=0x103f533
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*freelist).read(0xc420076a20, 0x254564000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/freelist.go:236 +0x37 fp=0xc42014ae80 sp=0xc42014add0 pc=0x11d42e7
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).loadFreelist.func1()
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:290 +0x12b fp=0xc42014aed0 sp=0xc42014ae80 pc=0x11dca6b
sync.(*Once).Do(0xc420272150, 0xc42014af18)
	/usr/local/go/src/sync/once.go:44 +0xbe fp=0xc42014af08 sp=0xc42014aed0 pc=0x106d18e
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).loadFreelist(0xc420272000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:283 +0x4e fp=0xc42014af38 sp=0xc42014af08 pc=0x11cf6de
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.Open(0xc4202620a0, 0x4c, 0x180, 0xc42014b010, 0x100fe49, 0xc420086078, 0x8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:260 +0x38e fp=0xc42014afd8 sp=0xc42014af38 pc=0x11cf30e
github.com/NebulousLabs/Sia/persist.OpenDatabase(0x16c397e, 0x16, 0x16adc91, 0x5, 0xc4202620a0, 0x4c, 0xc42014b0d8, 0x10e151f, 0xc42014b138)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/boltdb.go:72 +0x7b fp=0xc42014b070 sp=0xc42014afd8 pc=0x11e028b
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).openDB(0xc420180780, 0xc4202620a0, 0x4c, 0xc4202620a0, 0x4c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/database.go:76 +0x6f fp=0xc42014b0e8 sp=0xc42014b070 pc=0x139848f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc420180780, 0xc420072390, 0xc420084200)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:27 +0xa5 fp=0xc42014b168 sp=0xc42014b0e8 pc=0x139d515
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc420180780, 0xc42017c4e0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:88 +0x16c fp=0xc42014b1c8 sp=0xc42014b168 pc=0x139d73c
github.com/NebulousLabs/Sia/modules/consensus.NewCustomConsensusSet(0x175f060, 0xc4200ea6e0, 0x1, 0xc420020700, 0x3f, 0x1760580, 0xc42000a3a0, 0x2, 0xc420020700, 0x3f)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:148 +0x570 fp=0xc42014b4b8 sp=0xc42014b1c8 pc=0x1396020
github.com/NebulousLabs/Sia/modules/consensus.New(0x175f060, 0xc4200ea6e0, 0x1, 0xc420020700, 0x3f, 0x1b, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:102 +0x71 fp=0xc42014b518 sp=0xc42014b4b8 pc=0x1395a71
main.(*Server).loadModules(0xc4200b80f0, 0x16eb728, 0xc4200c82a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:504 +0x1c81 fp=0xc42014b9c0 sp=0xc42014b518 pc=0x1556e11
main.startDaemon(0x0, 0x0, 0x7ffeefbffcc7, 0xe, 0x7ffeefbffcf3, 0x5, 0x7ffeefbffce2, 0x5, 0x0, 0x7ffeefbffd49, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:188 +0x2b3 fp=0xc42014bbc0 sp=0xc42014b9c0 pc=0x15512a3
main.startDaemonCmd(0xc4200f3b80, 0xc4200ae460, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162 fp=0xc42014bcb0 sp=0xc42014bbc0 pc=0x1551932
github.com/spf13/cobra.(*Command).execute(0xc4200f3b80, 0xc42008c010, 0x5, 0x5, 0xc4200f3b80, 0xc42008c010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:766 +0x2c1 fp=0xc42014bda0 sp=0xc42014bcb0 pc=0x1258101
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200f3b80, 0x16dba5a, 0x3b, 0xc4200ada40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:852 +0x30a fp=0xc42014bee0 sp=0xc42014bda0 pc=0x1258cba
github.com/spf13/cobra.(*Command).Execute(0xc4200f3b80, 0x1b19e00, 0x16c2910)
	/home/luke/go/src/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc42014bf10 sp=0xc42014bee0 pc=0x125898b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x6fe fp=0xc42014bf88 sp=0xc42014bf10 pc=0x155226e
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc42014bfe0 sp=0xc42014bf88 pc=0x102b4b2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42014bfe8 sp=0xc42014bfe0 pc=0x1057e61

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 4 [chan receive]:
main.startDaemon.func1(0xc42001c6c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:171 +0x38
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:170 +0x186

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x1cdbf00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420142298, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420142298, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420142280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420142280, 0x1001197, 0xc4201943a0, 0x15e7b80)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000c0d8, 0x10548e0, 0xc420054ea0, 0xc420054ea8)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c0d8, 0x16eb8d8, 0xc420194320, 0x175b000, 0xc420076210)
	/usr/local/go/src/net/tcpsock.go:259 +0x49
net/http.(*Server).Serve(0xc420099450, 0x175a440, 0xc42000c0d8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2770 +0x1a5
main.(*Server).Serve(0xc4200b80f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:608 +0x44
main.startDaemon.func2(0xc4200c82a0, 0xc4200b80f0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:186 +0x2b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:185 +0x2a2

goroutine 6 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedSaveLoop(0xc4200ea6e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/persist.go:57 +0x10b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:251 +0x577

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x1cdbbc0, 0x72, 0xc420056a28)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420192218, 0x72, 0xffffffffffffff00, 0x17565a0, 0x1a03498)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420192218, 0xc420025900, 0x8, 0x8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420192200, 0xc420025950, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420192200, 0xc420025950, 0x8, 0x8, 0xc420154e20, 0xc420056b70, 0x105013d)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000c138, 0xc420025950, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
io.ReadAtLeast(0x1ce0150, 0xc42000c138, 0xc420025950, 0x8, 0x8, 0x8, 0x15c2c20, 0x1, 0xc420025950)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1ce0150, 0xc42000c138, 0xc420025950, 0x8, 0x8, 0x8, 0x16045e0, 0x1688548)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/NebulousLabs/Sia/encoding.ReadPrefix(0x1ce0150, 0xc42000c138, 0x64, 0x100e258, 0x1604580, 0x1688500, 0x0, 0x1ce0150)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:13 +0x97
github.com/NebulousLabs/Sia/encoding.ReadObject(0x1ce0150, 0xc42000c138, 0x15af5c0, 0xc42017c620, 0x64, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:28 +0x43
github.com/NebulousLabs/Sia/modules/gateway.connectVersionHandshake(0x175d500, 0xc42000c138, 0x16adcc3, 0x5, 0xc42000c138, 0x0, 0x0, 0x156e010)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:309 +0x203
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc4200ea6e0, 0xc4201fea20, 0x12, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:434 +0x25b
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc4200ea6e0, 0xc4201fea20, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0xf8
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc4200700c0, 0xc4200ea6e0, 0xc4201fea20, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:136 +0x449

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x1cdbd60, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420142318, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420142318, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420142300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420142300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000c118, 0x1028759, 0x8, 0xc420064040)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c118, 0x16ebd00, 0xc4200c8360, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:259 +0x49
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentListen(0xc4200ea6e0, 0xc4200c8360)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:117 +0x75
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:303 +0xa70

goroutine 8 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedSleep(0xc4200ea6e0, 0x12a05f200, 0xc4200700c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:164 +0xf5
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager(0xc4200ea6e0, 0xc4200c83c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:154 +0x466
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:310 +0xb12

goroutine 9 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodeManager(0xc4200ea6e0, 0xc4200c8420)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:292 +0x152
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:317 +0xbbd

goroutine 10 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodePurger(0xc4200ea6e0, 0xc4200c8480)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:227 +0x1ae
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:324 +0xc68

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x1cdbaf0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420142518, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420142518, 0xc42017e800, 0x800, 0x800)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420142500, 0xc42017e800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:207 +0x17d
net.(*netFD).readFrom(0xc420142500, 0xc42017e800, 0x800, 0x800, 0x162b2c0, 0x0, 0x0, 0x20, 0x20)
	/usr/local/go/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc42000c130, 0xc42017e800, 0x800, 0x800, 0xc420201fe0, 0xc420095d40, 0xc4200258b9, 0x4)
	/usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000c130, 0xc42017e800, 0x800, 0x800, 0x3, 0xc420201fe0, 0x2, 0x4, 0x0)
	/usr/local/go/src/net/udpsock.go:118 +0x6f
github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do(0xc420201f80, 0xc4200e6600, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:102 +0x6b8
github.com/NebulousLabs/go-upnp/goupnp/ssdp.SSDPRawSearchCtx(0x175af80, 0xc420024098, 0xc420201f80, 0x16d6478, 0x2f, 0x2, 0x3, 0x13e6efb9892de60d, 0x1592326e45f5a67b, 0xb2298a4c90cae54, ...)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/ssdp/ssdp.go:58 +0x508
github.com/NebulousLabs/go-upnp/goupnp.DiscoverDevicesCtx(0x175af80, 0xc420024098, 0x16d6478, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/goupnp.go:72 +0xee
github.com/NebulousLabs/go-upnp/goupnp.NewServiceClientsCtx(0x175af80, 0xc420024098, 0x16d6478, 0x2f, 0x8, 0xc420025890, 0xc42005ad80, 0x114e514, 0x1388, 0x962, ...)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/service_client.go:33 +0x67
github.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1.NewWANPPPConnection1Clients(0x175af80, 0xc420024098, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1/internetgateway1.go:2861 +0x62
github.com/NebulousLabs/go-upnp.DiscoverCtx(0x175af80, 0xc420024098, 0xc420065480, 0xc4200ea810, 0xc420238ee0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:140 +0x92
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x16eb378, 0xc4200ea7c8)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:126 +0x39
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedForwardPort(0xc4200ea6e0, 0xc4200256c9, 0x4)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:117 +0x8b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:327 +0xc9f

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x1cdbc90, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420142398, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420142398, 0xc42017f000, 0x800, 0x800)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadFrom(0xc420142380, 0xc42017f000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:207 +0x17d
net.(*netFD).readFrom(0xc420142380, 0xc42017f000, 0x800, 0x800, 0x162b2c0, 0x0, 0x0, 0x20, 0x20)
	/usr/local/go/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc42000c120, 0xc42017f000, 0x800, 0x800, 0xc420270020, 0xc420095da0, 0xc4200258f9, 0x4)
	/usr/local/go/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc42000c120, 0xc42017f000, 0x800, 0x800, 0x3, 0xc420270020, 0x2, 0x4, 0x0)
	/usr/local/go/src/net/udpsock.go:118 +0x6f
github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do(0xc420201ea0, 0xc4200e6500, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:102 +0x6b8
github.com/NebulousLabs/go-upnp/goupnp/ssdp.SSDPRawSearchCtx(0x175af80, 0xc420024098, 0xc420201ea0, 0x16d6478, 0x2f, 0x2, 0x3, 0x9ff41afe673fffc2, 0x38692e2f2df66826, 0x188e394612afecf1, ...)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/ssdp/ssdp.go:58 +0x508
github.com/NebulousLabs/go-upnp/goupnp.DiscoverDevicesCtx(0x175af80, 0xc420024098, 0x16d6478, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/goupnp.go:72 +0xee
github.com/NebulousLabs/go-upnp/goupnp.NewServiceClientsCtx(0x175af80, 0xc420024098, 0x16d6478, 0x2f, 0x8, 0xc420025878, 0xc420058d78, 0x114e514, 0x1388, 0xd94, ...)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/service_client.go:33 +0x67
github.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1.NewWANPPPConnection1Clients(0x175af80, 0xc420024098, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/dcps/internetgateway1/internetgateway1.go:2861 +0x62
github.com/NebulousLabs/go-upnp.DiscoverCtx(0x175af80, 0xc420024098, 0xc42007e040, 0xc4200ea810, 0xc4202396d8)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:140 +0x92
github.com/NebulousLabs/go-upnp.Discover(0xc400000008, 0x16eb378, 0xc4200ea7c8)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/upnp.go:126 +0x39
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedLearnHostname(0xc4200ea6e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:59 +0x8b
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:328 +0xcc4

goroutine 14 [select]:
github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do.func1(0xc4200c84e0, 0xc4200e6500, 0xc420201ea0)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:79 +0xed
created by github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:78 +0x3cb

goroutine 15 [select]:
github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do.func1(0xc4200c8540, 0xc4200e6600, 0xc420201f80)
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:79 +0xed
created by github.com/NebulousLabs/go-upnp/goupnp/httpu.(*HTTPUClient).Do
	/home/luke/go/src/github.com/NebulousLabs/go-upnp/goupnp/httpu/httpu.go:78 +0x3cb
