### ISSUE TITLE
'Feature Request has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by gianco83** [NebulousLabs/Sia#3169]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by gianco83** [comment]
this is the error log

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.13724701 seconds

Wallet: scanned to height 141056...
Wallet: scanned to height 141124...
Wallet: scanned to height 141195...
Wallet: scanned to height 141260...
Wallet: scanned to height 141335...
Wallet: scanned to height 141398...
Wallet: scanned to height 141455...
Wallet: scanned to height 141531...
Wallet: scanned to height 141608...
Wallet: scanned to height 141687...
Wallet: scanned to height 141757...
Wallet: scanned to height 141835...
Wallet: scanned to height 141908...
Wallet: scanned to height 141977...
Wallet: scanned to height 142051...
Wallet: scanned to height 142126...
Wallet: scanned to height 142202...
Wallet: scanned to height 142276...
Wallet: scanned to height 142339...
Wallet: scanned to height 142406...
Wallet: scanned to height 142477...
Wallet: scanned to height 142550...
Wallet: scanned to height 142620...
Wallet: scanned to height 142691...
Wallet: scanned to height 142763...goroutine 1 [running]:
runtime/debug.Stack(0x1043db7, 0x0, 0xc42340d960)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42340dad0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7ffeefbffc72, 0xe, 0x7ffeefbffc9e, 0x5, 0x7ffeefbffc8d, 0x5, 0x0, 0x7ffeefbffcf9, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x53c
main.startDaemonCmd(0xc4200fdb80, 0xc42009e550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200fdb80, 0xc4200a0010, 0x5, 0x5, 0xc4200fdb80, 0xc4200a0010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200fdb80, 0x16dba5a, 0x3b, 0xc4200c1900)
	/home/luke/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4200fdb80, 0x1b19e00, 0x16c2910)
	/home/luke/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x6fe
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.
